### ISSUE TITLE
Alert on wrong version

### ISSUE THREAD

**Issue by Mte90** [llaville/php-compat-info#121]
I develop plugins for wordpress but the minimum requirement is PHP 5.2.4.
I check weekly the minimum version but is possible get an alert that report the wrong line for the minimum requirement?
Now i scan manually in search of anonymous function and other things.

**Comment by Mte90** [comment]
The parameter --php not exist anymore in phpcompatinfo 4.x there is a way to check for the minimum version?

**Comment by llaville** [comment]
Yes used the filter feature - See http://php5.laurent-laville.org/compatinfo/manual/current/en/developer-guide--filters.html

**Comment by Mte90** [comment]
Well the command was very useful and fast respect a custom filters.
Maybe create a plugin is better with the configuration in phpcompatinfo.json.

**Comment by llaville** [comment]
Command was very limited, and filter with closure allow to customize all (or almost) data to return / render.

**Comment by Mte90** [comment]
an example for create a check by parameters?

**Comment by llaville** [comment]
I am not sure  to have well understood your needs. Coul you explains more please ?

**Comment by Mte90** [comment]
like in the old version, with a parameter choose the minimum php version to scan

**Comment by llaville** [comment]
The filter feature available in version 4.x offer much more possibily that `--php` option on `analyser:run` in version 3.x
While in version 3 you could only filter results on  PHP versions, v4 allow you to filter all parts of result report.  This is the main reason that there is no equivalent with `--php` option.

Please use, `--filter` option in command line as explained in doc (already referencedin this thread)

**Comment by Mte90** [comment]
Thank you!
I have updated the instructions https://github.com/Mte90/WordPress-Plugin-Boilerplate-Powered/wiki/How-use-the-Scripts-and-CLI-tools and added a file in my project.
