### ISSUE TITLE
Global constants defined with `const` are not properly analyzed

### ISSUE THREAD

**Issue by cmb69** [llaville/php-compat-info#168]
I've noticed that global constants defined with the `const` keyword are reported as requiring PHP 4.0.0, but they are allowed only since PHP 5.3.0; in earlier version that is a [syntax error](http://3v4l.org/vJaWe).

Test script:

    <?php
    const FOO = 42;

`php phpcompatinfo-4.0.0-beta3.phar analyser:run .`

    Constants Analysis

        Constant  Matches REF  EXT min/Max PHP min/Max
        FOO       1       user             4.0.0
        Total [1]                          4.0.0

**Comment by llaville** [comment]
Better explain http://stackoverflow.com/questions/2447791/define-vs-const than the syntax error link
