### ISSUE TITLE
Wrong php version detected with phpcompatinfo-3.7.3

### ISSUE THREAD

**Issue by temp** [llaville/php-compat-info#169]
My code uses \DateTimeImmutable::createFromMutable(), which was added to php in 5.6.0.
But phpcompatinfo detects minimum php version 5.5:

```
Global Analysis

                    Count Cond PHP min Elements highlight
 Extensions         4     0    5.5.0   date
 Namespaces         2     0    5.5.0   +global
 Interfaces         1     0    5.1.0   Countable
 Traits             0     0
 Classes            8     0    5.5.0   DateTimeImmutable
 User Functions     0     0
 Internal Functions 1     0    4.0.0   count
 Constants          3     0    4.0.0   false
 Total                         5.5.0
```

**Comment by llaville** [comment]
Hello Stephan,

php-compatinfo 3.7 is already reached end-of-life. I won't maintain it  for references elements versions.

The new version 4.0.0-RC1 available since 2015-03-04 solved this issue, and add many improvements, such as speed, memory comsumption, PHP 5.6 support and lot more.

Data dictionnary is now on a local SQLite3 database built from a series of JSON files (see `data
/references` folder). 
Build the latest version with command 
    
    php data\handleDB.php db:init

I suggest you to test the new version, or if don't want to, wait for the stable release that is planned for 2015-04-04

For example, with code source 
```php 
<?php
$date = new DateTime("2014-06-20 11:45 Europe/London");

$immutable = DateTimeImmutable::createFromMutable( $date );
```

4.0.0-RC1 give such output

    Data Source Analysed

    Directories                                          1
    Files                                                1

    Extensions Analysis

        Extension Matches REF  EXT min/Max PHP min/Max
        Core              Core 4.0.0       5.6.0beta1
        date              date 5.2.0       5.2.0
        Total [2]                          5.6.0beta1

    Namespaces Analysis

        Namespace Matches REF  EXT min/Max PHP min/Max
        +global           Core 5.6.0beta1  5.6.0beta1
        Total [1]                          5.6.0beta1

    No interface found

    No trait found

    Classes Analysis

        Class             Matches REF  EXT min/Max PHP min/Max
        DateTime          1       date 5.2.0       5.2.0
        DateTimeImmutable 1       date 5.5.0       5.5.0
        Total [2]                                  5.5.0

    No function found

    No constant found

    No condition found

    Requires PHP 5.6.0beta1 (min)

**Comment by temp** [comment]
Thanks for your info!
Just tried it with phpcompatinfo-4.0.0-RC1.phar, but I still get minimum version 5.5.0, which is wrong.

Code:
```
$ ack createFromMutable WorkloadResolver.php
                        $to = \DateTimeImmutable::createFromMutable($to);
                        $from = \DateTimeImmutable::createFromMutable($from);
                        $to = \DateTimeImmutable::createFromMutable($to);
```

compatinfo:
```
$ phpcompatinfo-4.0.0-RC1.phar analyser:run WorkloadResolver.php

Data Source Analysed

Directories                                          1
Files                                                1

Extensions Analysis

    Extension Matches REF  EXT min/Max PHP min/Max
    Core              Core 5.1.0       5.1.0
    date      1       date 5.5.0       5.5.0
    Total [2]                          5.5.0

Namespaces Analysis

    Namespace                           Matches REF  EXT min/Max PHP min/Max
    +global                                     Core             4.0.0
    Controlling\EmployeeBundle\Workload         user             5.5.0
    Total [2]                                                    5.5.0

No interface found

No trait found

Classes Analysis

    Class                                                Matches REF  EXT min/Max PHP min/Max
  U Controlling\EmployeeBundle\Entity\Employee           4       user             5.3.0
  U Controlling\EmployeeBundle\Workload\Period           3       user             5.3.0
  U Controlling\EmployeeBundle\Workload\PeriodCollection 1       user             5.3.0
    Controlling\EmployeeBundle\Workload\WorkloadResolver         user             5.5.0
  U Controlling\Period\PeriodInterface                   1       user             5.3.0
    DateInterval                                         1       date 5.3.0       5.3.0
    DateTimeImmutable                                    6       date 5.5.0       5.5.0
  U Doctrine\Common\Collections\Collection               1       user             5.3.0
    Exception                                            4       Core 5.1.0       5.1.0
    Total [9]                                                                     5.5.0

No function found

Constants Analysis

    Constant  Matches REF  EXT min/Max PHP min/Max
    false     4       Core 4.0.0       4.0.0
    null      6       Core 4.0.0       4.0.0
    true      2       Core 4.0.0       4.0.0
    Total [3]                          4.0.0

No condition found

Requires PHP 5.5.0 (min)
```

Doesn't phpcompatinfo check method calls?

**Comment by llaville** [comment]
YES, phpcompatinfo is able to check method calls !

With only the snippet code provided 
```php
<?php
  $to = \DateTimeImmutable::createFromMutable($to);
  $from = \DateTimeImmutable::createFromMutable($from);
  $to = \DateTimeImmutable::createFromMutable($to);
  ```
I got results as follow 

    Data Source Analysed

    Directories                                          1
    Files                                                1

    Extensions Analysis

        Extension Matches REF  EXT min/Max PHP min/Max
        Core              Core 4.0.0       5.6.0beta1
        Total [1]                          5.6.0beta1

    Namespaces Analysis

        Namespace Matches REF  EXT min/Max PHP min/Max
        +global           Core 5.6.0beta1  5.6.0beta1
        Total [1]                          5.6.0beta1

    No interface found

    No trait found

    Classes Analysis

        Class             Matches REF  EXT min/Max PHP min/Max
        DateTimeImmutable 3       date 5.5.0       5.5.0
        Total [1]                                  5.5.0

    No function found

    No constant found

    No condition found

    Requires PHP 5.6.0beta1 (min)

Is it possible to have access to full code (if public) to check what's wrong ?

**Comment by temp** [comment]
Here's a small test case.

Test.php:
```php
<?php

namespace Test;

class Tester
{
    public function test(\DateTime $date)
    {
        $to = \DateTimeImmutable::createFromMutable($date);

        return $to->format('Y-m-d');
    }
}

$t = new Tester();
echo $t->test(new \DateTime()).PHP_EOL;
```

Results:

```bash
$ php56 Test.php
2015-03-20

$ php55 Test.php
PHP Fatal error:  Call to undefined method DateTimeImmutable::createFromMutable() in /.../Test.php on line 9

$ phpcompatinfo-4.0.0-RC1.phar analyser:run Test.php

Data Source Analysed

Directories                                          1
Files                                                1

Extensions Analysis

    Extension Matches REF  EXT min/Max PHP min/Max
    Core              Core 4.3.10      4.3.10
    date      1       date 5.2.0       5.2.0
    Total [2]                          5.2.0

Namespaces Analysis

    Namespace Matches REF  EXT min/Max PHP min/Max
    +global           Core             4.0.0
    Test              user             5.3.0
    Total [2]                          5.3.0

No interface found

No trait found

Classes Analysis

    Class             Matches REF  EXT min/Max PHP min/Max
    DateTime          2       date 5.2.0       5.2.0
    DateTimeImmutable 1       date 5.5.0       5.5.0
    Test\Tester       1       user             5.3.0
    Total [3]                                  5.5.0

No function found

Constants Analysis

    Constant  Matches REF  EXT min/Max PHP min/Max
    PHP_EOL   1       Core 4.3.10      4.3.10
    Total [1]                          4.3.10

No condition found

Requires PHP 5.3.0 (min)
```

**Comment by llaville** [comment]
Thanks for the test case. I'll have a look on this issue ASAP.
Bug fixe should be include in 4.0.0-RC2 that will support also latest PHP versions (5.6.7, 5.5.23, 5.4.39)

**Comment by temp** [comment]
thanks!

**Comment by llaville** [comment]
Before to publish the RC2 tomorrow, I'll try to explain the current situation, and the solution implemented.

First, let me said that RC1 is already able to detect PHP version on each class method.
If we used the test case code example you've provided Stephan, and ativate the verbose level 3 (`-vvv`), you can check it yourself.

Of course it's not enough, so this is the reason I've worked to improve the current solution and propose : 

- ability to see PHP versions on each class/interface/trait methods (with verbose level 1 or 2)
- still suggest PHP min version (to keep compatibility with previous versions)
- add a new info about PHP version that tell us which version is required when all features are used

In our test case example, it will give something like 

        Data Source Analysed

    Directories                                          1
    Files                                                1

    Extensions Analysis

        Extension Matches REF  EXT min/Max PHP min/Max PHP all
        Core              Core 4.3.10      4.3.10
        date      1       date 5.6.0beta1  5.6.0beta1
        Total [2]                          5.6.0beta1

    Namespaces Analysis

        Namespace Matches REF  EXT min/Max PHP min/Max PHP all
        +global           Core             4.0.0
        Test              user             5.3.0       5.6.0beta1
        Total [2]                          5.3.0       5.6.0beta1

    No interface found

    No trait found

    Classes Analysis

        Class                      Matches REF  EXT min/Max PHP min/Max PHP all
        DateTime                   2       date 5.2.0       5.2.0
        DateTimeImmutable          1       date 5.5.0       5.5.0
        function createFromMutable 1       date 5.6.0beta1  5.6.0beta1
        Test\Tester                1       user             5.3.0       5.6.0beta1
        function test                      user             5.6.0beta1
        Total [3]                                           5.5.0       5.6.0beta1                                         5.5.0       5.6.0beta1

    No function found

    Constants Analysis

        Constant  Matches REF  EXT min/Max PHP min/Max PHP all
        PHP_EOL   1       Core 4.3.10      4.3.10
        Total [1]                          4.3.10

    No condition found

    Requires PHP 5.3.0 (min), PHP 5.6.0beta1 (all)

Why a such solution. Don't forget that in OOP a class may be used without using all features (methods).

It's not yet perfect, and I need again to do more tests but it's a promising solution.
Feel free to give any feedback.
  
I'll push the commit just after

**Comment by llaville** [comment]
About my comment 
> Don't forget that in OOP a class may be used without using all features (methods).

Here is a real concrete example. Have a look on cakePHP 3.0

class constructor required PHP 5.4.0 (min), due to array short syntax 
https://github.com/cakephp/cakephp/blob/3.0/src/Auth/AbstractPasswordHasher.php#L42

`needsRehash()` method requires PHP 5.5.0, due to [password_needs_rehash](http://www.php.net/manual/en/function.password-needs-rehash.php) function
https://github.com/cakephp/cakephp/blob/3.0/src/Auth/AbstractPasswordHasher.php#L76

And with compatibility analyser, that will give something like 

    Classes Analysis

        Class                                                      Matches REF        EXT min/Max PHP min/Max PHP all 

        Cake\Auth\AbstractPasswordHasher                           3       user                   5.4.0       5.5.0   
        function __construct                                               user                   5.4.0               
        function hash                                                      user                   5.0.0               
        function check                                                     user                   5.0.0               
        function needsRehash                                               user                   5.5.0               

CakePHP requires PHP 5.4.16 min but if you used basic features, but need more for all

**Comment by llaville** [comment]
I'm pretty satisfied of results provided. it's up to users now to tell me if there are agree with this !

**Comment by temp** [comment]
Looks good!
I'll checkout branch 4.0 later, and will test it.

**Comment by temp** [comment]
Works fine!

**Comment by llaville** [comment]
Solution available in https://github.com/llaville/php-compat-info/releases/tag/4.0.0-RC2
