### ISSUE TITLE
Constant scalar expression detection

### ISSUE THREAD

**Issue by m6w6** [llaville/php-compat-info#170]
I think there is a missing negation at https://github.com/llaville/php-compat-info/blob/master/src%2FBartlett%2FCompatInfo%2FAnalyser%2FAbstractAnalyser.php#L328 which marks any scalar constant in a namespace as a constant facilitating scalar *expressions*.

So

    <?php
    namespace foo;
    const bar = "foo";

is wrongly marked with 5.6.0

and

    <?php
    namespace foo;
    const bar = "foo" . "bar";

is marked with 5.4.0

**Comment by llaville** [comment]
This bug affect only php-compatinfo 3.7 versions. That is I remember is in end-of-life situation.

php-compatinfo 4.0.0-RC2 give the right results, and is not affected by this issue.

I'll certainly release  a 3.7.4 but without date planned (it's not my priority; I'm focus on new major version 4.0 that should be released stable on April 4)

**Comment by llaville** [comment]
I've followed origin of issue. 
It came from commit https://github.com/llaville/php-compat-info/commit/a0218a8b6d443eed347cfb9d52b454c32b3d1e5a, that was a bad fix for issue GH-144.

Origin is not there, but on php-reflect 2.6  https://github.com/llaville/php-reflect/blob/master/src/Bartlett/Reflect/Builder.php#L647

So to fix this current issue, and avoid regression with GH-144, I'll have to publish a new version of php-reflect and also a new version of php-compatinfo.

This is the main reason that let me rewrite the new API 4.0 that simplify such architecture.

As I've said, this is not my priority, but this comment will help me to remember later, when I'll have time to do it.

BTW, I encourage all users to migrate to php-compatinfo 4.0 (currently in RC2) and stable is planned for April 4 2015.

**Comment by m6w6** [comment]
Sorry, I thought I was running 4.0, and sorry again, but I have to put off my rant here. Installing this overengineered bulk with composer is a nightmare; this is the composer line that made it actually work:

`composer global require bartlett/php-compatinfo=4.0.x-dev bartlett/php-reflect=3.0.x-dev nikic/php-parser=~1.1`

Now, it still bails out, and I have no idea why:

    █ mike@smugmug:~/src/pharext.git<git=master...origin/master [ahead 4]>$phpcompatinfo analyser:run src

    "compatibility" Analyser is not installed.
    █ mike@smugmug:~/src/pharext.git<git=master...origin/master [ahead 4]>$ phpcompatinfo analyser:list

     Analyser Name Analyser Class                           
     reflection    Bartlett\Reflect\Analyser\ReflectionAnalyser
     structure     Bartlett\Reflect\Analyser\StructureAnalyser
     loc           Bartlett\Reflect\Analyser\LocAnalyser    
    █ mike@smugmug:~/src/pharext.git<git=master...origin/master [ahead 4]> $ cat phpcompatinfo.json
    {
        "source-providers": [
            {
                "in": "src",
                "name": "/\\.(php|inc|phtml)$/"
            }
        ],
        "plugins": [
        ],
        "analysers": [
        ],
        "services": [
        ]
    }
   

Running the phar works, though.

**Comment by llaville** [comment]
If you want to install the source code, here is a solution that works 

Clone the repo either with HTTPS, invoking command 

    git clone https://github.com/llaville/php-compat-info.git

Or SSH 

    git clone git@github.com:llaville/php-compat-info.git

Then on the `php-compat-info`, invoke composer to install dependencies required

    cd php-compat-info
    php composer.phar install

**Comment by llaville** [comment]
@m6w6 as announced in my previous comment https://github.com/llaville/php-compat-info/issues/170#issuecomment-86687898, a php-reflect 2.6.3 has just been released, and a php-compatinfo 3.7.4 will follow soon.

In context of a Long Term Support (that will be ended on December 2015).

Now final stable release php-reflect 3.0.0, and fnal stable release php-compatinfo 4.0.0 are available, I consider previous versions deprecated, and release new versions only on regressions

**Comment by llaville** [comment]
php-compatinfo 3.7.4 is now available.
