### ISSUE TITLE
Idea: add "optional" in the DB.

### ISSUE THREAD

**Issue by remicollet** [llaville/php-compat-info#183]
This could simplify some tests.
(of course only for "really" optional, not those related to OS or to external library version)

**Comment by llaville** [comment]
I'm thinking about a concept, that will solve only the unit tests, but allow to solve platform conflicts.

Availalble on Linux, but not on Windows (see sphinx extension https://github.com/llaville/php-compat-info/issues/174#issuecomment-88409783), or depending of a PHP build conf (see redis extension https://github.com/llaville/php-compat-info/issues/174#issuecomment-88398968).

And also  #185, and probably more ...

**Comment by llaville** [comment]
Optional elements WILL NOT be solved by solution (see https://github.com/llaville/php-compat-info/issues/191#issuecomment-99420784) that will fixed only library version condition.

**Comment by llaville** [comment]
No solution for 4.2.0; will be delay to another release

**Comment by llaville** [comment]
Will be incuded in new project `php-compatinfo-db`. See announcement in https://github.com/llaville/php-compat-info/issues/208#issuecomment-147059222

**Comment by llaville** [comment]
Use of external project is considered as API BC break, so it won't be included in a 4.x series. Will be only available for 5.0

**Comment by llaville** [comment]
Feature was introduced in php-compatinfo-db. See https://github.com/llaville/php-compatinfo-db/commit/dde205117c01bdfab3a5f2ef170446942e5b9cbd 
Only constants are supported, and cURL extension referenced these first optional constants. See https://github.com/llaville/php-compatinfo-db/commit/7e1beec4370075c5fbe3cbc1ced691b6ecf4dea3

TestCase should, and will be clean-up in next days

**Comment by llaville** [comment]
Communications continue on php-compatinfo-db project / issue
