### ISSUE TITLE
Class methods are missing in v4

### ISSUE THREAD

**Issue by joshuaspence** [llaville/php-compat-info#184]
In version 3, PHP CompatInfo would include information about class methods. It seems that this data is missing in version 4.

**Comment by llaville** [comment]
Evan, 
I've not understood your request, until I see your script. 

The `reference:show` API did not provided yet the class or interface methods compatibility informations.

But to avoid any misunderstanding, the new major version 4.0 will take care of class methods versions in compatibility analysis phase. Details are visible on CLI if you set at least the verbose level 1 (`-v`) .

**Comment by llaville** [comment]
Implemented and available in repo. See commit https://github.com/llaville/php-compat-info/commit/596a631de377eecc3fdbc95e4bd50cb186233dc0

In CLI, here is an example with `date` extension 

    phpcompatinfo reference:show --methods date 

Will output something like 

    Methods                              EXT min/Max PHP min/Max
     DateInterval::__construct            5.3.0       5.3.0
     DateInterval::__set_state            5.3.0       5.3.0
     DateInterval::__wakeup               5.3.0       5.3.0
     DateInterval::createFromDateString   5.3.0       5.3.0
     DateInterval::format                 5.3.0       5.3.0
     DatePeriod::__construct              5.3.0       5.3.0
     DatePeriod::__set_state              5.3.0       5.3.0
     DatePeriod::__wakeup                 5.3.0       5.3.0
     DatePeriod::getDateInterval          5.3.0       5.6.5RC1
     DatePeriod::getEndDate               5.3.0       5.6.5RC1
     DatePeriod::getStartDate             5.3.0       5.6.5RC1
     DateTime::__construct                5.2.0       5.2.0
     DateTime::__set_state                5.2.0       5.2.0
     DateTime::__wakeup                   5.2.0       5.2.0 => 5.4.37
     DateTime::add                        5.2.0       5.3.0
     DateTime::createFromFormat           5.2.0       5.3.0
     DateTime::diff                       5.2.0       5.3.0 => 5.4.37
     DateTime::format                     5.2.0       5.2.0 => 5.4.37
     DateTime::getLastErrors              5.2.0       5.3.0
     DateTime::getOffset                  5.2.0       5.2.0 => 5.4.37
     DateTime::getTimestamp               5.2.0       5.2.0 => 5.4.37
     DateTime::getTimezone                5.2.0       5.2.0 => 5.4.37
     DateTime::modify                     5.2.0       5.2.0
     DateTime::setDate                    5.2.0       5.2.0
     DateTime::setISODate                 5.2.0       5.2.0
     DateTime::setTime                    5.2.0       5.2.0
     DateTime::setTimestamp               5.2.0       5.3.0
     DateTime::setTimezone                5.2.0       5.2.0
     DateTime::sub                        5.2.0       5.3.0
     DateTimeImmutable::__construct       5.5.0       5.5.0
     DateTimeImmutable::__set_state       5.5.0       5.5.0
     DateTimeImmutable::add               5.5.0       5.5.0
     DateTimeImmutable::createFromFormat  5.5.0       5.5.0
     DateTimeImmutable::createFromMutable 5.6.0beta1  5.6.0beta1
     DateTimeImmutable::getLastErrors     5.5.0       5.5.0
     DateTimeImmutable::modify            5.5.0       5.5.0
     DateTimeImmutable::setDate           5.5.0       5.5.0
     DateTimeImmutable::setISODate        5.5.0       5.5.0
     DateTimeImmutable::setTime           5.5.0       5.5.0
     DateTimeImmutable::setTimestamp      5.5.0       5.5.0
     DateTimeImmutable::setTimezone       5.5.0       5.5.0
     DateTimeImmutable::sub               5.5.0       5.5.0
     DateTimeInterface::__wakeup          5.5.0       5.5.0
     DateTimeInterface::diff              5.5.0       5.5.0
     DateTimeInterface::format            5.5.0       5.5.0
     DateTimeInterface::getOffset         5.5.0       5.5.0
     DateTimeInterface::getTimestamp      5.5.0       5.5.0
     DateTimeInterface::getTimezone       5.5.0       5.5.0
     DateTimeZone::__construct            5.2.0       5.2.0
     DateTimeZone::__set_state            5.2.0       5.2.0
     DateTimeZone::__wakeup               5.2.0       5.2.0
     DateTimeZone::getLocation            5.2.0       5.3.0
     DateTimeZone::getName                5.2.0       5.2.0
     DateTimeZone::getOffset              5.2.0       5.2.0
     DateTimeZone::getTransitions         5.2.0       5.2.0
     DateTimeZone::listAbbreviations      5.2.0       5.2.0
     DateTimeZone::listIdentifiers        5.2.0       5.2.0
     Total [57]

     Static methods                       EXT min/Max PHP min/Max
     DateInterval::__set_state            5.3.0       5.3.0
     DateInterval::createFromDateString   5.3.0       5.3.0
     DatePeriod::__set_state              5.3.0       5.3.0
     DateTime::__set_state                5.2.0       5.2.0
     DateTime::createFromFormat           5.2.0       5.3.0
     DateTime::getLastErrors              5.2.0       5.3.0
     DateTimeImmutable::__set_state       5.5.0       5.5.0
     DateTimeImmutable::createFromFormat  5.5.0       5.5.0
     DateTimeImmutable::createFromMutable 5.6.0beta1  5.6.0beta1
     DateTimeImmutable::getLastErrors     5.5.0       5.5.0
     DateTimeZone::__set_state            5.2.0       5.2.0
     DateTimeZone::listAbbreviations      5.2.0       5.2.0
     DateTimeZone::listIdentifiers        5.2.0       5.2.0
     Total [13]

And of course, give the summary count, if you invoke command

    phpcompatinfo reference:show date

    Reference Summary
      Releases                                           8
      INI entries                                        5
      Constants                                         14
      Functions                                         48
      Interfaces                                         1
      Classes                                            5
      Methods                                           57
      Static Methods                                    13
