### ISSUE TITLE
Add sniff for new reserved words in PHP7

### ISSUE THREAD

**Issue by fabiang** [llaville/php-compat-info#186]
PHP7 will reserve some keywords for class-, interface-, trait names and namespaces:
- [PHP RFC: Reserve More Types in PHP 7](https://wiki.php.net/rfc/reserve_more_types_in_php_7)
- [PHP RFC: Reserve Even More Types in PHP 7](https://wiki.php.net/rfc/reserve_even_more_types_in_php_7)

Would be a nice feature if phpcs could have a sniff for those keywords

**Comment by llaville** [comment]
Sure, but no date due because PHP 7 is still under development

**Comment by llaville** [comment]
Will be add later in 5.1, because I've no free time to have a chance to implement these sniffs.
And as I want to release today the final stable version 5.0 of php-compatinfo with sniff architecture and its new migration analyser.

**Comment by llaville** [comment]
Finally, i've aborted dev of branch 5.1, to a reworks on new major version 6.0

Sniff arch was dropped in profit of simple node visitor patterns. More news will come soon !

**Comment by llaville** [comment]
Finally Sniff architecture is kept and gave us a chance to solve the situation !

**Comment by llaville** [comment]
Will be included in upcoming release 5.4.0 (under active development)

**Comment by llaville** [comment]
First code reorganization phase is now applied (see https://github.com/llaville/php-compat-info/issues/266#issuecomment-659302135).
Next step is to fix the `KeywordReservedSniff` to solve this issue/report.

**Comment by llaville** [comment]
In waiting release of 5.4.0RC1, the current branch 5.4 solved this issue. A `ForbiddenSniff` will be add very soon to complete list of reserved keywords 

* https://www.php.net/manual/en/reserved.keywords.php

**Comment by llaville** [comment]
`ForbiddenSniff` is impossible to be introduces in v5.4 easily. So it's deferred to major version  6.0
