### ISSUE TITLE
Composer installation fails to install compatibility analyser

### ISSUE THREAD

**Issue by cmb69** [llaville/php-compat-info#187]
When using phpcompatinfo-4.0.0.phar the output of `phpcompatinfo analyser:list` is as shown in the [user guide](http://php5.laurent-laville.org/compatinfo/manual/current/en/user-guide--commands.html). However, when I install via Composer the compatibility analyser is missing. This happens even though I used a local composer install (to avoid any inadvertent dependencies):

    {
        "require-dev": {
            "bartlett/php-compatinfo": "4.0.*"
        }
    }

**Comment by llaville** [comment]
Fixed in php-reflect project. 
Will be released with reflect 3.0.1 and compatinfo 4.0.1
