### ISSUE TITLE
Enhance GenericTest

### ISSUE THREAD

**Issue by llaville** [llaville/php-compat-info#189]
Following Remi's work begun with PR #172, I've another implementation that will be publish on a new branch called `generictest` to avoid conflict with current stable version.

Everybody are encourage to give their feedback.

Roadmap. 
- push the new branch tomorrow (2015-04-10) with all extensions fixed.
- push monday  (2015-04-13) a new phpunit console printer more human readable than the standard, what is a bit unreadable without debug mode.

**Comment by llaville** [comment]
Some explains : 

Running the full unit test suites with the `phpunit.xml.dist` took a long time on my laptop (Windows dual core 2Ghz).
- 2 min 20 sec before the phpunit progress bar appears (phase initialization, create test and count them through the data provider - phpunit standard behavior)
- 4 min 40 sec total later the result displayed

OK, but incomplete, skipped, or risky tests!
Tests: 200374, Assertions: 6955, Skipped: 1648.

And now, let have a look deeper on code : 

* GenericTest is not a real concrete class, so to avoid error by just running it, it was transformed to abstract.

        abstract class GenericTest extends \PHPUnit_Framework_TestCase

* Some constants to identify elements for the generic reference checker function `checkValuesFromReference()` 
        
        const REF_ELEMENT_INI       = 1;
        const REF_ELEMENT_CONSTANT  = 2;
        const REF_ELEMENT_FUNCTION  = 3;
        const REF_ELEMENT_INTERFACE = 4;
        const REF_ELEMENT_CLASS     = 5;

* concrete extension is create on `GenericTest::__construct()`, following naming test convention (so no constant or other name definition required). 

```php
<?php

    public function __construct($name = null, array $data = array(), $dataName = '')
    {
        parent::__construct($name, $data, $dataName);

        $parts = explode('\\', get_class($this));

        self::$ext = $name = strtolower(
            str_replace('ExtensionTest', '', end($parts))
        );

        // special case(s)
        if ('zendopcache' === $name) {
            self::$ext = $name = 'zend opcache';
        }

        self::$obj = new ExtensionFactory($name);
    }

```    

* A generic data provider for all reference's elements

```php
<?php

    public function provideReferenceValues($methodName)
    {
        if ('testGetIniEntriesFromReference' === $methodName) {
            $elements = self::$obj->getIniEntries();

        } elseif ('testGetFunctionsFromReference'  === $methodName) {
            $elements = self::$obj->getFunctions();

        } elseif ('testGetConstantsFromReference'  === $methodName) {
            $elements = self::$obj->getConstants();

        } elseif ('testGetClassesFromReference' == $methodName) {
            $elements = self::$obj->getClasses();

        } elseif ('testGetInterfacesFromReference' == $methodName) {
            $elements = self::$obj->getInterfaces();

        } else {
            $elements = array();
        }

        $this->assertTrue(is_array($elements));

        if (empty($elements)) {
            // do not fails suite if no test case found in data provider
            $this->markTestSkipped(
                sprintf(
                    'No tests found in suite "%s::%s".',
                    get_class($this),
                    $methodName
                )
            );
        }

        $dataset = array();
        foreach ($elements as $name => $range) {
            $dataset[] = array($name, $range);
        }
        return $dataset;
    }

```

* A unique location to check reference elements (avoid code dupplicate, because almost equals)

```php
<?php

    protected function checkValuesFromReference($element, $range, &$optional, &$ignored, $refElementType)
    {
        if (in_array($range['ext.min'], self::$optionalreleases)) {
            return;
        }

        $min = $range['php.min'];
        $max = $range['php.max'];

        if (array_key_exists('php.excludes', $range)) {
            if (in_array(PHP_VERSION, $range['php.excludes'])) {
                // We are in min/max, so add it as optional
                array_push($optional, $element);
            }
        }
        if (!in_array($element, $optional)
            && (empty($min) || version_compare(PHP_VERSION, $min) >= 0)
            && (empty($max) || version_compare(PHP_VERSION, $max) <= 0)
        ) {
            // Should be there except if set as optional
            $this->assertShouldBeThere($element, $refElementType);
        }
        if (!in_array($element, $ignored)) {
            if (($min && version_compare(PHP_VERSION, $min) < 0)
                || ($max && version_compare(PHP_VERSION, $max) > 0)
            ) {
                // Should not be there except if ignored
                $this->assertShouldNotBeThere($element, $refElementType, $min, $max);
            }
        }
    }

```

* Two custom assert functions to check values of a single reference element

```php
<?php

    protected function assertShouldBeThere($element, $refElementType)
    {
        if (self::REF_ELEMENT_INI == $refElementType) {
            $this->assertNotSame(
                ini_get($element),
                false,
                "INI '$element', found in Reference, does not exists."
            );

        } elseif (self::REF_ELEMENT_FUNCTION == $refElementType) {
            $this->assertTrue(
                function_exists($element),
                "Function '$element', found in Reference, does not exists."
            );

        } elseif (self::REF_ELEMENT_CONSTANT == $refElementType) {
            $this->assertTrue(
                defined($element),
                "Constant '$element', found in Reference, does not exists."
            );

        } elseif (self::REF_ELEMENT_CLASS == $refElementType) {
            $this->assertTrue(
                class_exists($element, false),
                "Class '$element', found in Reference, does not exists."
            );

        } elseif (self::REF_ELEMENT_INTERFACE == $refElementType) {
            $this->assertTrue(
                interface_exists($element, false),
                "Interface '$element', found in Reference, does not exists."
            );
        }
    }

    protected function assertShouldNotBeThere($element, $refElementType, $min, $max)
    {
        if (self::REF_ELEMENT_INI == $refElementType) {
            $this->assertFalse(
                ini_get($element),
                "INI '$element', found in Reference ($min,$max), exists."
            );

        } elseif (self::REF_ELEMENT_FUNCTION == $refElementType) {
            $this->assertFalse(
                function_exists($element),
                "Function '$element', found in Reference ($min,$max), exists."
            );

        } elseif (self::REF_ELEMENT_CONSTANT == $refElementType) {
            $this->assertFalse(
                defined($element),
                "Constant '$element', found in Reference ($min,$max), exists."
            );

        } elseif (self::REF_ELEMENT_CLASS == $refElementType) {
            $this->assertFalse(
                class_exists($element, false),
                "Class '$element', found in Reference ($min,$max), exists."
            );

        } elseif (self::REF_ELEMENT_INTERFACE == $refElementType) {
            $this->assertFalse(
                interface_exists($element, false),
                "Interface '$element', found in Reference ($min,$max), exists."
            );
        }
    }

```

* And dont forget to see implementation of test themself with the generic data provider. E.g : 

```php
<?php

    /**
     * Test than all referenced ini entries exists
     *
     * @dataProvider provideReferenceValues
     * @group  reference
     * @return void
     */
    public function testGetIniEntriesFromReference($name, $range)
    {
        $this->checkValuesFromReference(
            $name,
            $range,
            self::$optionalcfgs,
            self::$ignoredcfgs,
            self::REF_ELEMENT_INI
        );
    }

```

**Comment by llaville** [comment]
The new phpunit console printer will follow [example](https://github.com/llaville/phpunit-LoggerTestListener/commit/1b3f6d3ec4b2d60a7c2dbadd947feefb44b1b800) provided in future bartlett/phpunit-loggertestlistener 1.3.0

**Comment by llaville** [comment]
The first public version of phpunit printer console is available !

Compare between standard console printer :  

    phpunit.phar -c phpunit.xml  tests\Reference\Extension\AmqpExtensionTest.php

That ouput something like 

    PHPUnit 4.6.4 by Sebastian Bergmann and contributors.

    Configuration read from C:\home\github\php-compat-info\phpunit.xml

    ............S...................................S

    Time: 2.81 seconds, Memory: 12.00Mb

    OK, but incomplete, skipped, or risky tests!
    Tests: 49, Assertions: 276, Skipped: 2.

And the php-compatinfo / phpunit printer console 

    phpunit.phar  -c phpunit.xml --printer=Bartlett\Tests\CompatInfo\ResultPrinter tests\Reference\Extension\AmqpExtensionTest.php

That output something like 

    PHPUnit 4.6.4 by Sebastian Bergmann and contributors.

    Configuration read from C:\home\github\php-compat-info\phpunit.xml

    TestSuite 'Bartlett\Tests\CompatInfo\Reference\Extension\AmqpExtensionTest' started.
    TestSuite 'AmqpExtensionTest::testGetIniEntriesFromReference'
        OK. Tests: 11, Assertions: 11
    TestSuite 'AmqpExtensionTest::testGetFunctionsFromReference'
    Test 'Bartlett\Tests\CompatInfo\Reference\Extension\AmqpExtensionTest::testGetFunctionsFromReference' has been skipped.
        OK. Tests: 1, Assertions: 0, Skipped: 1
    TestSuite 'AmqpExtensionTest::testGetConstantsFromReference'
        OK. Tests: 20, Assertions: 20
    TestSuite 'AmqpExtensionTest::testGetClassesFromReference'
        OK. Tests: 10, Assertions: 10
    TestSuite 'AmqpExtensionTest::testGetInterfacesFromReference'
    Test 'Bartlett\Tests\CompatInfo\Reference\Extension\AmqpExtensionTest::testGetInterfacesFromReference' has been skipped.
        OK. Tests: 1, Assertions: 0, Skipped: 1
    TestSuite 'Bartlett\Tests\CompatInfo\Reference\Extension\AmqpExtensionTest' ended has been skipped.
    Results OK. Tests: 49, Assertions: 276, Skipped: 2

Try also with `--verbose` and `--debug` switches that are also supported (even with unsupported arguments. See https://github.com/sebastianbergmann/phpunit/issues/1674)

TIP: It used a trait (https://github.com/llaville/php-compat-info/blob/generictest/tests/ResultPrinter.php#L14-L44). So be aware to run test suites with PHP 5.4.0 or better !

NOTE: `--colors` is not yet supported (by the trait)

This is all. All feedback are welcome

**Comment by llaville** [comment]
NOTE: `--printer` switch was used only for comparaison demo. You may also put in in the `phpunit.xml` file. Entry is  `<phpunit printerClass="Bartlett\\Tests\\CompatInfo\\ResultPrinter"`

**Comment by llaville** [comment]
Two weeks that this improvement to unit test suites was proposed and no feedback yet. 
Lack of interest time period, again for two more weeks, and I'll cancel this feature !

**Comment by remicollet** [comment]
See issue #191 #192 and #193 which show that this feature is useful to get a complete report in a single pass (which was nearly impossible to achieve with standard test suite: 1 run , 1 failure, 1 fix... iterate)

**Comment by remicollet** [comment]
Le soucis, c'est le temps.

Un premier fix (je gagne 10%, mais j'ai un max. d'extensions chargées)

    diff --git a/tests/Reference/GenericTest.php b/tests/Reference/GenericTest.php
    index 5613c2b..1efdb85 100644
    --- a/tests/Reference/GenericTest.php
    +++ b/tests/Reference/GenericTest.php
    @@ -148,7 +148,9 @@ abstract class GenericTest extends \PHPUnit_Framework_TestCase
          */
         public function provideReferenceValues($methodName)
         {
    -        if ('testGetIniEntriesFromReference' === $methodName) {
    +        if (!extension_loaded(self::$ext)) {
    +            $elements = array();
    +        } else if ('testGetIniEntriesFromReference' === $methodName) {
                 $elements = self::$obj->getIniEntries();
     
             } elseif ('testGetFunctionsFromReference'  === $methodName) {

**Comment by llaville** [comment]
I've just finished my new console logger version that will requires [bartlett/phpunit-loggertestlistener](https://github.com/llaville/phpunit-LoggerTestListener) 1.5.0 (not yet released).

Compares between standard PHPUnit printer console and mine are almost equal, but with more more I'll try to explain on a post I'll publish later in my blog. I'll keep you aware.

In summary 

PHPUnit STD printer 
```
Time: 2.67 minutes, Memory: 44.50Mb

OK, but incomplete, skipped, or risky tests!
Tests: 4069, Assertions: 5960, Skipped: 434.
```

My CONSOLE printer that may used any PSR-3 logger compatible
```
Time: 2.79 minutes, Memory: 45.25Mb, References: 105

Results OK. Tests: 4069, Assertions: 5960, Skipped: 434
```

WARNING: That will excluded of course test failures already notified by Remi

**Comment by llaville** [comment]
In waiting release of bartlett/phpunit-loggertestlistener 1.5.0, and new post of blog project that will explain in detail the new PHPUnit printer class, code are available on recent commits https://github.com/llaville/php-compat-info/compare/c600cc3b5c...444dbe3ea4

**Comment by llaville** [comment]
All explains about the new console logger (PHPUnit printer class) are available on post http://php5.laurent-laville.org/compatinfo/blog/201505-PHPUnit-ResultPrinter.html

**Comment by llaville** [comment]
Commit https://github.com/llaville/php-compat-info/commit/bb043a24b55eb1ed42b31f642bdfbb87a4c3ac02 solved an issue reported https://github.com/sebastianbergmann/phpunit/issues/1707

@remicollet My current results are on my Windows Laptop
````
Time: 6.94 minutes, Memory: 83.25Mb, References: 105

Results OK. Tests: 7130, Assertions: 8094, Skipped: 315
````
The current printer class for php-compatinfo (27e312d) is configured with Monolog, printing results on CLI console and saving all PHPUnit events in a local file ('phpunit-phpcompatinfo.log'). 

All explains are in my post on blog project (see previous comment)

**Comment by llaville** [comment]
On my point of view the generic test part with it's new console (PHPUnit printer class based on a logger concept) is now over. 
Awaiting your feedback, only about this purpose, and not the failed tests that will be proceed in their own issue reports

**Comment by llaville** [comment]
Seems lack of interest from the community, so t won't be include in future 4.2.0

**Comment by llaville** [comment]
Result Printer class for PHPUnit is independant from GenericTest refactoring, and was [included](https://github.com/llaville/php-compat-info/commit/70b9cb434f97343ff1e0f53a6e3ca94adf9d835b) in master branch for future 4.2.0 release

**Comment by llaville** [comment]
Will be part of new project. See https://github.com/llaville/php-compat-info/issues/208#issuecomment-122490988, and https://github.com/llaville/php-compat-info/issues/208#issuecomment-147059222

**Comment by llaville** [comment]
Idea re-activated

**Comment by llaville** [comment]
Use of external project is considered as API BC break, so it won't be included in a 4.x series. Will be only available for 5.0

**Comment by llaville** [comment]
Avaiable on php-compatinfo-db project. See https://github.com/llaville/php-compatinfo-db/commit/a1c6707eaf7e273bc9bcc98a737e2234d0ec1b1c

**Comment by llaville** [comment]
php-compatinfo-db with its 105 extensions and at least 4800 unit tests is long if you consider to run standard PHPUnit version 4 or 5. Reason is PHPUnit counts all tests before to execute them.

I've found an alternative with phing. See https://github.com/llaville/php-compatinfo-db/commit/23230c749bc92efb29a15a7137d06fb08280a9ea
Beware of PHPUnit issue linked.
