### ISSUE TITLE
Static method calls don't properly adjust total requirements

### ISSUE THREAD

**Issue by cmb69** [llaville/php-compat-info#194]
Consider the following script:

    <?php
    
    Normalizer::normalize('foo');

Running `phpcompatinfo analyser:run .` (PHAR version 4.1.0), class `Normalizer` is correctly detected to require PHP 5.3.0alpha1, but the total requirements are reported as:

    Requires PHP 4.0.0 (min), PHP 4.0.0 (all)

**Comment by llaville** [comment]
Reason is that `intl` extension reference is not yet fully documented (methods are missing).

FYI: All references that are already fully documented are defined in the `GenericTest` : see https://github.com/llaville/php-compat-info/blob/4.0/tests/Reference/GenericTest.php#L57-L87

**Comment by llaville** [comment]
If you want to test it, DO NOT forget to rebuild the database. Invoke the following command on php-compatinfo folder

    php data/handleDB.php db:init

It will create a new fresh copy of `compatinfo.sqlite` that will replace the current distribution of 4.1.0

**Comment by cmb69** [comment]
Works great! Thanks.
