### ISSUE TITLE
Absolutely namespaced classes not properly detected with class_exists()

### ISSUE THREAD

**Issue by cmb69** [llaville/php-compat-info#195]
Consider the following script:

    <?php

    if (class_exists('\Normalizer')) {
        \Normalizer::normalize('foo');
    }

Running phpcompatinfo analyser:run . (PHAR version 4.1.0), I get the following (partial) output:

        Class       Matches REF  EXT min/Max PHP min/Max PHP all
        Normalizer  1       intl 1.0.0beta   5.3.0alpha1
     CU \Normalizer         user             5.3.0

I would expect, however, something like:

        Class      Matches REF  EXT min/Max PHP min/Max PHP all
     C  Normalizer 1       intl 1.0.0beta   5.3.0alpha1

This is, by the way, the result I'm getting when omitting the leading backslash from both class names in the  script.

**Comment by llaville** [comment]
As explained in #194, the `intl` reference with missing methods is not yet able to detect the right version for `\Normalizer::normalize('foo')`. 
I must document it before  to check other fixes !

**Comment by llaville** [comment]
Thanks Christoph for your report. It will allow me to improve again conditional code detection.

When a class is detected previously as optional, all methods are also tagged as optional to avoid bad total requirements
