### ISSUE TITLE
Only report when above a certain version

### ISSUE THREAD

**Issue by GaryJones** [llaville/php-compat-info#197]
If the output contains many lines, trying to find that one instance of 5.4 amongst all of the 4.0.0 lines is a little painful.

Could there be a flag where only entries that have a min requirement above that flag value are shown? i.e. `phpcompatinfo analyser:run . --min 5.4.0`

**Comment by llaville** [comment]
Ok will add the same feature as for API `reference:show` , see the `--filter` option

An example is availalable on examples folder https://github.com/llaville/php-compat-info/blob/4.0/examples/api_reference_show.php

**Comment by llaville** [comment]
This feature will be soon available, just after release of php-reflect 3.1.0 that will propose such base function for all analysers

**Comment by llaville** [comment]
php-reflect 3.1 has just been release. Filter feature for CompatInfo will be equals to Reflect. See details in http://php5.laurent-laville.org/reflect/blog/

**Comment by llaville** [comment]
No feedback. Sorry but it's now too late ! It will be added in final 4.2.0 without changes

**Comment by GaryJones** [comment]
Didn't know feedback was required, but next available release is fine, thanks!
