### ISSUE TITLE
Documentation for "all"

### ISSUE THREAD

**Issue by GaryJones** [llaville/php-compat-info#198]
I'm not clear on what the "all" column is for in the output and I couldn't find a clear explanation in the documentation.

Could this be clarified in the documentation please?

**Comment by llaville** [comment]
Will do !
In waiting that should be clarify in documentation, here is a summary : 

https://github.com/llaville/php-compat-info/issues/169#issuecomment-84898437

Tell me if it's enough or not as explains

**Comment by llaville** [comment]
Added a note about `PHP all` column in the user guide (running part).

Whithout feedback (as asked) it's difficult to see if it's enough !

**Comment by GaryJones** [comment]
I think the documentation does help, thanks :-)
