### ISSUE TITLE
Class inheritance lifts requirements to >= PHP 5.3.0

### ISSUE THREAD

**Issue by cmb69** [llaville/php-compat-info#199]
Please consider the following test script:

    <?php
    
    class Foo {}
    class Bar extends Foo {}

`phpcompatinfo-4.1.0.phar --analyser:run .` reports `Requires PHP 5.3.0 (min), PHP 5.3.0 (all)`, whereas this is supposed to be compatible with PHP 4.3 at least.

**Comment by llaville** [comment]
Nice catch, but why so restricted with PHP 4.3; I think it will be at least PHP 4.0

**Comment by llaville** [comment]
If you're agree with minimum PHP version 4.0.0, you can close this issue.

Thanks again for reporting, and help to improve again php-compatinfo

**Comment by cmb69** [comment]
Thanks for fixing so quickly. And yes, PHP 4.0.0 is fine: :)
