### ISSUE TITLE
goto statement is not checked

### ISSUE THREAD

**Issue by cmb69** [llaville/php-compat-info#200]
It seems that the usage of the [goto statement](http://php.net/manual/en/control-structures.goto.php) is not checked, but it's only available as of PHP 5.3.0. Consider the following script:

    <?php
    goto end;
    end:

`phpcompatinfo-4.1.0.phar analyser:run .` reports:

    Requires PHP 4.0.0 (min)

**Comment by llaville** [comment]
Thanks again for reporting Chistoph, and help to improve CompatInfo detection.

To all users: remember that the standard `compatibility` analyser is not a feature analyser, and in such way, it does not print PHP specific features and versions.
