### ISSUE TITLE
5.6.11 / ldap

### ISSUE THREAD

**Issue by remicollet** [llaville/php-compat-info#205]
New optional constant: LDAP_OPT_DIAGNOSTIC_MESSAGE introduced in 5.6.11RC1

     --- 5610	2015-06-28 07:15:03.666455142 +0200
     +++ 5611	2015-06-28 07:15:41.907627504 +0200
     @@ -1,4 +1,4 @@
     -Extension [ <persistent> extension #34 ldap version <no_version> ] {
     +Extension [ <persistent> extension #26 ldap version <no_version> ] {
      
        - INI {
          Entry [ ldap.max_links <SYSTEM> ]
     @@ -6,7 +6,7 @@
          }
        }
      
     -  - Constants [31] {
     +  - Constants [32] {
          Constant [ integer LDAP_DEREF_NEVER ] { 0 }
          Constant [ integer LDAP_DEREF_SEARCHING ] { 1 }
          Constant [ integer LDAP_DEREF_FINDING ] { 2 }
     @@ -32,6 +32,7 @@
          Constant [ integer LDAP_OPT_SERVER_CONTROLS ] { 18 }
          Constant [ integer LDAP_OPT_CLIENT_CONTROLS ] { 19 }
          Constant [ integer LDAP_OPT_DEBUG_LEVEL ] { 20481 }
     +    Constant [ integer LDAP_OPT_DIAGNOSTIC_MESSAGE ] { 50 }
          Constant [ integer LDAP_OPT_X_SASL_MECH ] { 24832 }
          Constant [ integer LDAP_OPT_X_SASL_REALM ] { 24833 }
          Constant [ integer LDAP_OPT_X_SASL_AUTHCID ] { 24834 }

**Comment by remicollet** [comment]
Notice: detected by Fedora CI, aka Koschei

See : 
* https://apps.fedoraproject.org/koschei/package/php-bartlett-PHP-CompatInfo
* https://kojipkgs.fedoraproject.org/work/tasks/730/10230730/build.log

**Comment by llaville** [comment]
Thanks for this alert Remi, I'll have a look later

**Comment by llaville** [comment]
Commit https://github.com/llaville/php-compat-info/commit/bc9c9abf4ff653105a441f22e9cc99eb816369b3 fixed this issue.
