### ISSUE TITLE
Failed tests current master

### ISSUE THREAD

**Issue by remicollet** [llaville/php-compat-info#208]
Tested with a71e44cf3fedf16ffbd8d299e824efd72a6b8daa

Fedora 22, php 5.6.11, most extension loaded:

    1) Bartlett\Tests\CompatInfo\Reference\Extension\AmqpExtensionTest::testGetConstantsFromExtension
    Defined constant 'PHP_AMQP_MAX_CHANNELS' not known in Reference.
    Failed asserting that an array has the key 'PHP_AMQP_MAX_CHANNELS'.
    2) Bartlett\Tests\CompatInfo\Reference\Extension\AmqpExtensionTest::testGetClassMethodsFromExtension
    Defined method 'AMQPConnection::preconnect' not known in Reference.
    Failed asserting that an array has the key 'preconnect'.

Notice : running amqp 1.6.0beta3

    3) Bartlett\Tests\CompatInfo\Reference\Extension\SphinxExtensionTest::testGetClassMethodsFromExtension
    Defined method 'SphinxClient::setFilterString' not known in Reference.
    Failed asserting that an array has the key 'setFilterString'.

Notice: running sphinx 1.3.3

Fedora 21/22, php 5.6.1, minimal set of extensions => OK.

Fedora 19/20, php 5.5.27, minimal set of extensions

    1) Bartlett\Tests\CompatInfo\Reference\Extension\CurlExtensionTest::testGetConstantsFromReference
    Constant 'CURL_HTTP_VERSION_2_0', found in Reference, does not exists.
    Failed asserting that false is true.

Notice: curl version, see http://rpms.famillecollet.com/rpmphp/zoom.php?rpm=curl

RHEL 7, php 5.4.43, minimal set of extensions => OK.

RHEL 6, php 5.4.43, minimal set of extensions

    1) Bartlett\Tests\CompatInfo\Reference\Extension\CurlExtensionTest::testGetConstantsFromReference
    Constant 'CURLINFO_LOCAL_IP', found in Reference, does not exists.
    Failed asserting that false is true.

    2) Bartlett\Tests\CompatInfo\Reference\Extension\LibxmlExtensionTest::testGetConstantsFromReference
    Constant 'LIBXML_HTML_NODEFDTD', found in Reference, does not exists.
    Failed asserting that false is true.

Notice: libxml version 2.7.6 

As first failed assertion stop test, cannot say if other issues exist.

**Comment by llaville** [comment]
**So No release 4.4.1 today :(**
 
To all users: if you want to get the latest fixed planned to be included (see milestone [4.4.1](https://github.com/llaville/php-compat-info/milestones/4.4.1)), so pick up the source code. No PHAR version will be build.

I don't plan to publish new versions on branch 4.4 (currently master) now. Just maintained the source code on repository only. 
I'm focus on next major version 5.0.0 (still compatible in syntax and features with 4.4) but refactoring `compatibility` analyser and add new `migration` analyser using the sniffs architecture explained in [RFC](https://github.com/llaville/php-compat-info/issues/202)

**Comment by remicollet** [comment]
I start thinking that the reference database should be maintained as a separated project, so can be updated when needed, without relation to reflect/compatinfo life cycle.

**Comment by llaville** [comment]
Remi, I've in mind to publish a new 4.5.0 release sunday evening. Probably they will still have tests failures on different Linux / Fedora versions.

Unit tests are important and I don't wish to minimize this part of my library, but those what are related to Reference are less important (for me) than the main features and old issue regression tests. 

I've in last phase of version 5.0 what will include the new sniff architecture, especially for the Migration Analyser.
I'd like to reintegrate also idea behind #189 but it should not be for the initial 5.0.0 (probably 5.1.0). 

The last source code version should be available tomorrow morning (if you have time to have a look)

**Comment by remicollet** [comment]
For now, I got (during initDb)

    [RuntimeException]                         
    Cannot decode file pthreads3.methods.json

**Comment by remicollet** [comment]
On Fedora 21

     PHPUnit 5.0.3 by Sebastian Bergmann and contributors.
     
     .............................................................   61 / 1265 (  4%)
     .............................................................  122 / 1265 (  9%)
     .............................................................  183 / 1265 ( 14%)
     .............................................................  244 / 1265 ( 19%)
     ...........................................................SS  305 / 1265 ( 24%)
     SSSSSSSSSS...................................................  366 / 1265 ( 28%)
     ................................SSSSSSSSSSSS.................  427 / 1265 ( 33%)
     F.....SSSSSSSSSSSS...........................................  488 / 1265 ( 38%)
     .............................................................  549 / 1265 ( 43%)
     .............................................................  610 / 1265 ( 48%)
     .............................................................  671 / 1265 ( 53%)
     .................................................SSSSSSSSSSSS  732 / 1265 ( 57%)
     .............................................................  793 / 1265 ( 62%)
     .............................................................  854 / 1265 ( 67%)
     .............................................................  915 / 1265 ( 72%)
     ............................................SSSSSSSSSSSS.....  976 / 1265 ( 77%)
     ............................................................. 1037 / 1265 ( 81%)
     .....................................................
     Warning: Cannot load module 'XCache' because conflicting module 'apc' is already loaded in Unknown on line 0
     SSSSSSSS 1098 / 1265 ( 86%)
     SSSS..F...................................................... 1159 / 1265 ( 91%)
     ............................................................. 1220 / 1265 ( 96%)
     .......................................
     
     Time: 2.23 seconds, Memory: 140.00Mb
     
     There were 2 failures:
     
     1) Bartlett\Tests\CompatInfo\Reference\Extension\LdapExtensionTest::testGetConstantsFromExtension
     Defined constant 'LDAP_OPT_TIMEOUT' not known in Reference.
     Failed asserting that an array has the key 'LDAP_OPT_TIMEOUT'.
     
     /dev/shm/BUILD/php-compat-info-03c8d2f50e8f3f5472d8f01da153b1cf1fb66932/tests/Reference/GenericTest.php:389
     
     2) Bartlett\Tests\CompatInfo\Reference\Extension\XdebugExtensionTest::testGetFunctionsFromReference
     Function 'xdebug_dump_function_trace', found in Reference, does not exists.
     Failed asserting that false is true.
     
     /dev/shm/BUILD/php-compat-info-03c8d2f50e8f3f5472d8f01da153b1cf1fb66932/tests/Reference/GenericTest.php:268

**Comment by remicollet** [comment]
On RHEL-7 (php 5.4.45)

    1) Bartlett\Tests\CompatInfo\Reference\Extension\StandardExtensionTest::testGetFunctionsFromReference
    Function 'php_logo_guid', found in Reference (4.0.0,5.4.44), exists.
    Failed asserting that true is false.

**Comment by remicollet** [comment]
On RHEL-6 (php 5.4.45)

     1) Bartlett\Tests\CompatInfo\Reference\Extension\CurlExtensionTest::testGetConstantsFromReference
     Constant 'CURLINFO_LOCAL_IP', found in Reference, does not exists.
     Failed asserting that false is true.
     
     /builddir/build/BUILD/php-compat-info-03c8d2f50e8f3f5472d8f01da153b1cf1fb66932/tests/Reference/GenericTest.php:347
     
     2) Bartlett\Tests\CompatInfo\Reference\Extension\LibxmlExtensionTest::testGetConstantsFromReference
     Constant 'LIBXML_HTML_NODEFDTD', found in Reference, does not exists.
     Failed asserting that false is true.
     
     /builddir/build/BUILD/php-compat-info-03c8d2f50e8f3f5472d8f01da153b1cf1fb66932/tests/Reference/GenericTest.php:347
     
     3) Bartlett\Tests\CompatInfo\Reference\Extension\StandardExtensionTest::testGetFunctionsFromReference
     Function 'php_logo_guid', found in Reference (4.0.0,5.4.44), exists.
     Failed asserting that true is false.
     
     /builddir/build/BUILD/php-compat-info-03c8d2f50e8f3f5472d8f01da153b1cf1fb66932/tests/Reference/GenericTest.php:278

**Comment by remicollet** [comment]
On Fedora 20 (PHP 5.5.30)

    1) Bartlett\Tests\CompatInfo\Reference\Extension\CurlExtensionTest::testGetConstantsFromReference
    Constant 'CURLCLOSEPOLICY_CALLBACK', found in Reference (4.0.2,5.5.28), exists.
    Failed asserting that true is false.

**Comment by llaville** [comment]
Thanks for testing Remi, but definitive code is not yet published on repo.

I'm still testing regression group tests that is my priority goal, especially for local fix about https://github.com/llaville/php-compat-info/issues/209. 
I know that there are issues with Reference but I will fix it only with 5.0, not 4.5

**Comment by llaville** [comment]
FYI : Will be in move this two days (no internet connection), and cannot read or push anything before sunday evening.

**Comment by llaville** [comment]
I've again regressions to fixed, so release 4.5.0 should come only tomorrow evening

**Comment by llaville** [comment]
Unit tests for group `regression` were just been fixed. Tomorrow I'll continue my tests in real applications to see if I found other errors.
I'll also fixed the latest PHP version 5.6.14, 5.5.30, 5.4.45 and generate documentation.

Release 4.5.0 is on good way !

**Comment by llaville** [comment]
I'll try to fix References in few hours, unless someone found a regresssion in current source code of version 4.5 available in repo.

**Comment by llaville** [comment]
Pthreads and Ldap References were fixed for Release 4.5.0

**Comment by llaville** [comment]
To solve issues related only to DB info, I've definitively adopted point of view of you @remicollet .

Next release 4.6.0 and 5.0.0 (what are delayed now) will use a new project `php-compatinfo-db`.
Same concept as PECL timezonedb.

I'll begin to work on this in next two days, and I should proposed an alpha version very soon now.

If you've other idea that could be integrated, dont' hesitate to share !

**Comment by llaville** [comment]
Empty project https://github.com/llaville/php-compatinfo-db was initialized.

**Comment by llaville** [comment]
Use of external project is considered as API BC break, so it won't be included in a 4.x series. Will be only available for 5.0

**Comment by llaville** [comment]
Branch 5.0 is available for testing with php-compatinfo-db 
I've not yet removed all components from php-compatinfo, but it used equiv in php-compatinfo-db

No more changes than just extract elements and transfer them to php-compatinfo-db. unit tests are still ok, without more supports as expected in final version.

**Comment by llaville** [comment]
As references are now extracted and transfered to php-compatinfo-db, if other issues exists, please open new bug report on project https://github.com/llaville/php-compatinfo-db
