### ISSUE TITLE
PHP feature detection versions overridden if any function defined after usage

### ISSUE THREAD

**Issue by bjork** [llaville/php-compat-info#209]
Declaring a new function seems to reset the versions to default ones, at least for versions updated by PHP features. `computePhpFeatureVersions` calls `updateLocalVersions` with correct versions, but when entering a new function those seem to get lost somehow.

It is easy to test by adding a line `function foo() {}` to the end of any of the test fixtures that `PhpFeaturesIssueTest` uses. All the tests fail after that change.

**Comment by llaville** [comment]
Sorry to reply so lately, but I was busy with my new job !
I've found a solution today, but I have to do regression tests before to publish new version 4.5.0 that will support also latest PHP 5.6, 5.5, 5.4 versions.

Next step is the release 5.0.0

**Comment by bjork** [comment]
Congrats for the new job!

Let me know if I can help in any way.

**Comment by llaville** [comment]
Release 4.5.0 was planned today, but it will be delayed to at least 1 more day.

**Comment by llaville** [comment]
I'll continue tomorrow my tests, (before officially released version 4.5) but it seems fixed now ! If you have time to test on your side, your help will be appreciated.
