### ISSUE TITLE
PHP 5.6 **-Operator not recognized

### ISSUE THREAD

**Issue by sudo-web** [llaville/php-compat-info#211]
Since PHP 5.6 there is the a alternative to the pow (Exponential expression)
e.g. you can use the ***-*Operator like this `10 ** 3` insted of `pow(10, 3)`
Unfortunately it is not recognized by php-compat-info Version 4.5.1

**Comment by llaville** [comment]
Currently only supported on branch 5.0 with migration analyser

**Comment by llaville** [comment]
I'll see how I can solved in 4.5 branch (currently master), for a possible 4.5.2
There won't have any 4.6 version.  Next one is 5.0

**Comment by llaville** [comment]
When Exponentiation is used as argument of function/method, CompatInfo 4.5.1 already detect it

```php
<?php
printf("2 ** 3 ==      %d\n", 2 ** 3);
```

But not yet with this syntax

```php
<?php
$a = 2;
$a **= 3;
printf("a ==           %d\n", $a);
```

**Comment by llaville** [comment]
Solution available with fix https://github.com/llaville/php-compat-info/commit/b871a8244864164b0e90d0340ec28b860efe8a17

Will be part of future 4.5.2 (no date planned yet)
