### ISSUE TITLE
Incoherent Min, Max and All values

### ISSUE THREAD

**Issue by patval** [llaville/php-compat-info#212]
Hi,

I'm new to Linux/PHP so sorry if my question is trivial.

I get contradicting information at the end of the php-combat-info report:

`Total [311]       5.3.0 => 4.4.9`
`Requires PHP 5.5.0 (min), PHP 4.4.9 (max), PHP 5.5.0 (all)`

Question: What is the real highest PHP version I can use ?

Thanks a lot for your help :)

Here's a dropbox link to the full report (txt file): https://www.dropbox.com/s/ibddd1lclkihuu1/FullReport.txt?dl=0

**Comment by llaville** [comment]
Hello @patval 

First, 
consider always to give your platform env (PHP version, Linux or Windows) and of course version of application you used. It's always true for all PHP soft and not just on CompatInfo. It will help lead dev to learn more about context issue.

Second, 
If you've analysed an open source code, please give an URL. Otherwise if it's a private application, could you give me how the `defined(T_ML_COMMENT)` is used.

Reason of 4.4.9 php max version, and I could give you either an awser of add to the issue todo list !

Thanks

**Comment by patval** [comment]
Hi,

my php version is:

PHP 5.4.45-0+deb7u2 (cli) (built: Oct 17 2015 08:26:31) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies

Linux:
PRETTY_NAME="Debian GNU/Linux 7 (wheezy)"

The version of compatinfo I used is 4.5.1

The application I’m using is a private application (that was done 5-6 years ago and I have no access to developper now).

As for the T_ML_COMMENT, as I am very, very new to linux and php, I have no idea what that is. I made a search for T_ML_COMMENT in my application files, and found only one file that contained that mention (T_ML_COMMENT). I am attaching that file to my answer.

At last, I don,t understand "Reason of 4.4.9 php max version”. Are you asking me what the reason is ? I have no idea. That was the last two lines if the report generated by Compat-Info. I was hoping you’d tell me.

Thank you very much

Patrick

**Comment by llaville** [comment]
`T_ML_COMMENT` was a constant used by the php tokenizer extension introduced in version PHP 4.2 and removed in version PHP 4.4.9
This is the reason of php max. But if your constant is conditionnaly used, it should not be counted in php.max (probably). But without source code example, I can't see the real use case and propose a fix for this situation. Hope you understand !

**Comment by patval** [comment]
Ok, I understand. What I can tell you though is that that code is currently running fine on another server that has PHP 5.3.3. So I am convinced the T_ML_COMMENT is not an issue.

However, in the results that I initially got from combat info, one line mentions 5.3.0 and the other mentions 5.5.0 as "min" or "all". I don't know what that means. 

I have a new server I would like to move the site to, and that's the server I ran php combat info on. I need to know if Apache must be rolled back to 5.3 or if it is not necessary.

How can I use Compat Info to know that ?

Patrick

**Comment by llaville** [comment]
You have to investigate yourself on components that were marked 5.5.0 min to see if it's really required or not.
To help you, consider to use the filter feature ( http://php5.laurent-laville.org/compatinfo/manual/current/en/developer-guide--filters.html ), there is an example that reduced reports to all elements >= 5.0.0 (change it to 5.5.0) and use the verbose mode level 2

```
$ phpcompatinfo analyser:run -vv --filter=YourFilters.php /path/to/your/source
```

**Comment by patval** [comment]
Thanks a lot Laurent.

I understand I am really too unexperimented to investigate my issue with your tool.

I really appreciate the help though.

Have a good day

Pat
