### ISSUE TITLE
PHP 5.6 constant expressons vs. static values is not detected in some cases

### ISSUE THREAD

**Issue by jack126guy** [llaville/php-compat-info#215]
[PHP 5.6 allows scalar expressions when previously only static values were allowed](http://php.net/manual/en/migration56.new-features.php) ("Constant expressions" section).

This is detected in the case of constants declared with `const`, but not for class properties or default function arguments.

For class properties, it is reported as requiring PHP 5.0.0:
```php
<?php
class MyClass {
    public static $two = 1 + 1;
}
```
[3v4l.org test](http://3v4l.org/hCXSc)

For default function arguments, it is reported as requiring PHP 4.0.0:
```php
<?php
function my_func($arg = 1 + 1) {
        //Do something
}
```
[3v4l.org test](http://3v4l.org/naUmh)

**Comment by llaville** [comment]
https://github.com/llaville/php-compat-info/commit/8e44d57b245343c186652618781a24d866199164 fixed this issue (wrong label 115)

**Comment by llaville** [comment]
Sorry for late reply and fixe.
Thanks for reporting this issue !
