### ISSUE TITLE
[RFE] display DB version

### ISSUE THREAD

**Issue by remicollet** [llaville/php-compat-info#216]
Instead of additionnally to its date.

```
phpCompatInfo version 5.0.0 DB built Jan 09 2016 15:19:56 CET
phpCompatInfo version 5.0.0 DB version 1.4.0 built Jan 09 2016 15:19:56 CET
```

**Comment by llaville** [comment]
FYI:  the version is already available with the `reference:list` command.

**Comment by remicollet** [comment]
Reference Database Version => 2016. 109.151956

This doesn't look like the version.

**Comment by remicollet** [comment]
FYI, fixed in Fedora packages:

```
$ phpcompatinfo --version
phpCompatInfo version 5.0.1 DB version 1.10.0 built Jul 05 2016 07:54:25 CEST
```

* http://pkgs.fedoraproject.org/cgit/rpms/php-bartlett-php-compatinfo-db.git/tree/php-bartlett-php-compatinfo-db-1.2.0-rpm.patch#n14
* http://pkgs.fedoraproject.org/cgit/rpms/php-bartlett-PHP-CompatInfo.git/tree/php-bartlett-PHP-CompatInfo-5.0.0-rpm.patch#n88

**Comment by llaville** [comment]
Good new : will be soon available

**Comment by llaville** [comment]
Release 5.0.2 is on good way for a publication very soon now.

Previous commit on branch 5.0, allow to have such result

phpCompatInfo version 5.0-dev DB version 1.15.0 built Nov 19 2016 16:19:38 CET
