### ISSUE TITLE
"::class" not detected as php 5.5

### ISSUE THREAD

**Issue by c33s** [llaville/php-compat-info#218]
it looks like the detection of "::class" is not working correctly. the ::class was introduced with php 5.5 http://php.net/manual/en/language.oop5.basic.php

i tried php-compat-info on the project https://github.com/vworldat/ContactFormBundle/issues/4 where it detected version 5.3

**Comment by llaville** [comment]
Sorry for late reply. This has just been fixed: see commit ed426da
