### ISSUE TITLE
Minimum PHP version wrong?

### ISSUE THREAD

**Issue by jyggen** [llaville/php-compat-info#219]
A couple of times over the past year (and once again today) I've used phpCompatInfo on a project and I really can't tell if I'm reading the output wrong or if the tool is bugging on me.

Here's an excerpt of the report:

```
Functions Analysis

    Function            Matches REF      EXT min/Max PHP min/Max
    array_map           1       standard 4.0.6       4.0.6
    array_merge         1       standard 4.0.0       4.0.0
    base_convert        2       standard 4.0.0       4.0.0
    constant            2       standard 4.0.4       4.0.4
    hash_file           1       hash     1.1         4.0.0
    implode             1       standard 4.0.0       4.0.0
    ip2long             1       standard 4.0.0       4.0.0
    json_decode         1       json     5.2.0       5.2.0
    json_encode         2       json     5.2.0       5.3.0
    json_last_error     2       json     5.3.0       5.3.0
    json_last_error_msg 2       json     5.5.0       5.5.0
    long2ip             1       standard 4.0.0       4.0.0
    sprintf             2       standard 4.0.0       4.0.0
    str_replace         1       standard 4.0.0       4.0.0
    str_split           1       standard 5.0.0       5.0.0
    strlen              1       Core     4.0.0       4.0.0
    strtoupper          1       standard 4.0.0       4.0.0
    sys_get_temp_dir    1       standard 5.2.1       5.2.1
    time                2       date     4.0.0       4.0.0
    Total [26]                                       5.5.0

No condition found

Requires PHP 5.4.0 (min), PHP 5.4.0 (all)
```

As seen the project is using `json_last_error_msg()` which was introduced in 5.5 (correctly stated under PHP min/Max). At the bottom however it says that the minimum PHP version is 5.4, which I assume is the summary for all analyzes and thus is wrong?

I'm running `phpCompatInfo version 5.0-dev DB built Feb 05 2016 22:19:07 CET` on OS X El Capitan (10.11) with the following PHP version:

```
PHP 7.0.3 (cli) (built: Feb  8 2016 00:54:22) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
```

Thanks!

**Comment by llaville** [comment]
Could you provide code or part of it that reproduced this issue please ?

**Comment by jyggen** [comment]
Absolutely. I'll try to isolate/reproduce it tomorrow.

**Comment by jyggen** [comment]
The following code reports 5.0 as minimum and all:

```php
<?php
class Foo
{
    public function decodeBaz($baz)
    {
        $baz = json_decode($baz);

        if (json_last_error() !== JSON_ERROR_NONE) {
            throw new \RuntimeException(json_last_error_msg());
        }

        return $baz;
    }

    public function getFoobar()
    {
        return 'foobar';
    }
}
```

If I remove the method `getFoobar()` it'll correctly report 5.5. If I move `getFoobar()` above `decodeBaz()` it'll also correctly state 5.5, so it seems like it only takes the last method in the class into consideration.

**Comment by llaville** [comment]
Thanks for the code sample : I'll have a look on it and reply to you ASAP

**Comment by llaville** [comment]
I'll analysed your code chunk with current code of branch 5.1, and it's reported as expected PHP 5.5

Please give it a try and reply to me if I may or not close this issue ! 

```
Platform : 
Windows PHP 7.0.3 and PHP 5.6.18
phpCompatInfo version 5.1-dev DB built Feb 05 2016 22:19:07 CET
```

**Comment by jyggen** [comment]
`phpCompatInfo version 5.1-dev DB built Feb 05 2016 22:19:07 CET` does indeed report PHP 5.5.
