### ISSUE TITLE
Using "$2y$" (Blowfish) on crypt doesn't trigger version 5.3.7

### ISSUE THREAD

**Issue by NemoStein** [llaville/php-compat-info#220]
Since 5.3.0, PHP contains implementations for some algorithms used in crypt.
From the docs:
> As of PHP 5.3.0, PHP contains its own implementation and will use that if the system lacks of support for one or more of the algorithms.

But Blowfish $2y$ is available since PHP 5.3.7

> 5.3.7	Added $2x$ and $2y$ Blowfish modes to deal with potential high-bit attacks.

PHP CompatInfo doesn't recognize this and doesn't report crypt as 5.3.7, nor 5.3.0, but 4.0.0 instead.

**Comment by llaville** [comment]
Could you provide a little sample script please ?

**Comment by NemoStein** [comment]
```
<?php
// test.php
$blowfish = crypt('password', '$2a$07$usesomesillystringforsalt$');
?>
```

> D:\test>phpcompatinfo analyser:run test.php
> 
> Data Source Analysed
> 
> Directories                                          1
> Files                                                1
> 
> Extensions Analysis
> 
>     Extension Matches REF      EXT min/Max PHP min/Max PHP all
>     Core              Core                 4.0.0
>     standard          standard 4.0.0       4.0.0
>     Total [2]                              4.0.0
> 
> Namespaces Analysis
> 
>     Namespace Matches REF  EXT min/Max PHP min/Max PHP all
>     +global           Core             4.0.0
>     Total [1]                          4.0.0
> 
> No interface found
> 
> No trait found
> 
> No class found
> 
> Functions Analysis
> 
>     Function  Matches REF      EXT min/Max PHP min/Max
>     crypt     1       standard 4.0.0       4.0.0
>     Total [1]                              4.0.0
> 
> No constant found
> 
> No condition found
> 
> Requires PHP 4.0.0 (min), PHP 4.0.0 (all)

**Comment by llaville** [comment]
Thanks a lot for all these details. I'll fix it ASAP !

**Comment by llaville** [comment]
A bit busy these past days, but I've finally found a solution.

**Comment by NemoStein** [comment]
This one was really easy to reproduce.
Just using a variable or concatenating a string to another breaks the analyser.

```
<?php
$a = "$2a$07$usesomesillystringforsalt";
$blowfish = crypt('password', $a);
?>
```

**Comment by llaville** [comment]
Sorry but this kind of code (with indirect reference) is impossible to detect by CompatInfo 5.1
This is not only for this case. All others that used variables as argument cannot be checked.

**Comment by NemoStein** [comment]
Oh, I see... Thank you for explaining. =]
