### ISSUE TITLE
Negative constants marked as PHP 5.6

### ISSUE THREAD

**Issue by trasher** [llaville/php-compat-info#222]
Hello,

When running compatinfo againt a class that contains negative constants, the minimum php version it set to 5.6.0; wich sounds incorrect.

For example with:
`<?php
class Foo {
	const BAR = -1;
}` ?>

We get the following:

     % phpcompatinfo analyser:run ./test.php            
    [...]
    Namespaces Analysis
    
        Namespace Matches REF  EXT min/Max PHP min/Max PHP all 
        +global           Core             5.6.0               
        Total [1]                          5.6.0               
    [...]
    Classes Analysis
    
        Class              Matches REF  EXT min/Max PHP min/Max PHP all 
        Foo                        user             5.6.0               
       U Html               2       user             4.0.0               
       extTranslationTest         user             4.0.0               
        Total [3]                                   5.6.0               
    [...]

**Comment by llaville** [comment]
Just back from hollidays. I'll have a look tomorrow !

**Comment by llaville** [comment]
Commit c5eb362 fixed the problem.

**Comment by trasher** [comment]
Thank you :)
