### ISSUE TITLE
5.0.2 phar does not detect yield / generators

### ISSUE THREAD

**Issue by dennisverspuij** [llaville/php-compat-info#226]
Hello, first of all thanks for this great utility!
When I run the phpcompatinfo-5.0.2.phar downloaded from your website on files with generators it does not seem to raise the minimum PHP version to 5.5.0 . For example running on the following code I get 4.0.0 as minimum version:
```
<?php
function x($x) { yield $x; }
```

What am I doing wrong?

Auto-Diagnose:

Checking php settings:
- Requires PHP 5.4.0 or better OK
- php.ini file loaded /etc/php.ini
- date extension loaded YES
- json extension loaded YES
- pcre extension loaded YES
- phar extension loaded YES
- reflection extension loaded YES
- spl extension loaded YES
- tokenizer extension loaded YES

**Comment by llaville** [comment]
Sorry for delay to reply. Much work at office, and less free times now !
I'll have a look this evening and I hope to publish a fix soon

**Comment by llaville** [comment]
Thanks for reporting. The new version 5.0.3 will be released in few minutes !

**Comment by dennisverspuij** [comment]
Fantastic, works, thanks!
