### ISSUE TITLE
use trait requires PHP 5.4.0

### ISSUE THREAD

**Issue by dennisverspuij** [llaville/php-compat-info#227]
Hi Laurent, I found another one, analyzing the following code should return PHP 5.4.0 as minimum for traits support (use statement in class), instead it returns 4.0.0:
```
<?php
class A { use B; }
```
Thanks

**Comment by llaville** [comment]
Thanks for this new bug report. Will fix it and release new version next monday (16)

**Comment by llaville** [comment]
Just been released new version 5.0.4. Thanks again Dennis for bug reporting !

**Comment by dennisverspuij** [comment]
You thanks again!
