### ISSUE TITLE
Support class constants 

### ISSUE THREAD

**Issue by JWZH** [llaville/php-compat-info#232]
Class constants of extensions are stored in [php-compatinfo-db](https://github.com/llaville/php-compatinfo-db), but they are not analysed in php-compat-info yet. Can we also analysis class constants ?

**Comment by llaville** [comment]
Can you provide a use case (with script example) please ?

**Comment by JWZH** [comment]
Actually we are using `php-compat-info` to retrieve all the defined built-in symbols in PHP. 
```php
use Bartlett\Reflect\Client;

$client = new Client();
$api = $client->api('reference');
$extensions = $api->dir();
$result = $api->show(
    $extension->name,
    $filter = false,
    $releases = false,
    $ini = false,
    $constants = true,
    $functions = true,
    $interfaces = true,
    $classes = true,
    $methods = true);
```
Would you recommend us to use `php-compatinfo-db` directly ?

**Comment by llaville** [comment]
Thanks to provide this use case. I know now what you want to get !

`php-compatinfo-db` is able to return class constants, but your're right not yet `php-compatinfo` 5.0.x

Will do it for the next release.

**Comment by llaville** [comment]
Release 5.0.8 will be publised tonight. php-compatinfo-db 1.23 was already released with some updates and new feature : same commands implemented in php-compatinfo (better location on my own opinion). 

For examples.

php data/handleDB.php db:list 

php data/handleDB.php db:show spl --class-constants

**Comment by llaville** [comment]
Just been released. Thanks for reporting !
Don't forget that commands are also available now on `php-compatinfo-db` package too
