### ISSUE TITLE
There are no commands defined in the "analyser" namespace

### ISSUE THREAD

**Issue by henno** [llaville/php-compat-info#234]
After doing exactly like in the guide, I get

$ phpcompatinfo analyser:run .

  [InvalidArgumentException]
  There are no commands defined in the "analyser" namespace.

**Comment by llaville** [comment]
Which version of php compatinfo do you use please ? (and what distrib ? source code, phar / what platform : php / linux / windows / mac ?

if you are on linux , is the result of `which` command expect the location of your phpcompatinfo installation ?
