### ISSUE TITLE
What's the letter in the fist column?

### ISSUE THREAD

**Issue by LucasKovacs** [llaville/php-compat-info#236]
Well as the question says, what that letter? What's indicating?

For example I get sometimes 'U', and in some others 'C'.

I went through the user documentation and command documentation and couldn't find what's the meaning of those.

**Comment by llaville** [comment]
The `U` tells (User) that component came from vendor sources and are not from main project files
The `C`tells (Conditional) that element is found on a conditional code

**Comment by llaville** [comment]
If we found one of these instructions (see https://github.com/llaville/php-compat-info/blob/master/src/Bartlett/CompatInfo/PhpParser/ConditionalCodeNodeProcessor.php#L45)
