### ISSUE TITLE
Function imagepng() is seen as requiring PHP 7.1.9

### ISSUE THREAD

**Issue by Thefirsh** [llaville/php-compat-info#241]
In the Functions Analysis section, the right column "EXT min/Max PHP min/Max" (why is there a max?) shows 7.1.9, like this:

`imagepng                          1       gd        4.0.0       7.1.9 `

I'm pretty sure that it doesn't require 7.1.9 nor did it get deprecated in 7.2.

**Comment by remicollet** [comment]
Probably because 7.2 is not yet supported

**Comment by Thefirsh** [comment]
What's the connection to that particular function? I ran this on the entire project and only that one thing popped out.

**Comment by remicollet** [comment]
Indeed something looks strange

```
   {
        "ext_name_fk": 18,
        "name": "imagepng",
        "ext_min": "4.0.0",
        "ext_max": "",
        "php_min": "4.0.0",
        "php_max": "",
        "parameters": "4.0.0, 4.0.0, 7.1.9, 7.1.9",
        "php_excludes": ""
    },

As from documentation

* 5.1.3 | Added the filters parameter.
* 5.1.2 | Added the quality parameter.



```

**Comment by remicollet** [comment]
Hmm... don't understand how this "parameters" is supposed to work

Another example, with json_encode

```
    {
        "ext_name_fk": 34,
        "name": "json_encode",
        "ext_min": "5.2.0",
        "ext_max": "",
        "php_min": "5.2.0",
        "php_max": "",
        "parameters": "5.2.0, 5.3.0, 5.5.0",
        "php_excludes": ""
    },
```

phpcompatinfo report

* `$a = json_encode($a); `=> 5.2.0 (OK)
* `$a = json_encode($a, $b); `=> 5.2.0 should be 5.3.0
* `$a = json_encode($a, $b, $c);` => 5.2.0 should be 5.5.0

**Comment by remicollet** [comment]
Forget previous... bad test on my side

**Comment by remicollet** [comment]
Easy fix 

```
-        "parameters": "4.0.0, 4.0.0, 7.1.9, 7.1.9",
+        "parameters": "4.0.0, 4.0.0, 5.1.2, 5.1.3",
```

@Thefirsh it didn't report any max version

```
Extensions Analysis

    Extension Matches REF  EXT min/Max PHP min/Max PHP all 
    Core              Core             4.0.0               
    gd                gd   4.0.0       7.1.9               
    Total [2]                          7.1.9               
```
But a bad minimal version.

**Comment by Thefirsh** [comment]
Thanks. I don't know how it would look like if it were showing a max version, never encountered that. Glad to know it seems like a bug and not my oversight. But how do I apply the fix and where? I installed the phar version using this line: `sudo mv phpcompatinfo-5.0.11.phar /usr/local/bin/phpcompatinfo`

**Comment by llaville** [comment]
The fix will be include in next release of php-compatinfo-db (1.29.0) that support all elements versions.
Will be soon, because PHP 7.1.14 has just been released.

Later I'll publish a new php-compatinfo version 5.0.12 that will include compatinfo-db 1.29

BTW, current phar version of compatinfo 5.0.11 include DB version 1.26

**Comment by llaville** [comment]
FIX already avaliable (see https://github.com/llaville/php-compatinfo-db/commit/7e5946e5026dfb103c15ee78ea6e3421632b17ec). 

Packages releases will follow !

Thanks to @Thefirsh  for reporting and @remicollet for analysis :)

**Comment by llaville** [comment]
Versions have just been released !
