### ISSUE TITLE
JSON config appears not to be respected

### ISSUE THREAD

**Issue by jrfnl** [llaville/php-compat-info#243]
With the following config in `phpcompatinfo.json`, files with an `.inc` extension are still analysed, even though the `name` entry explicitly demands that only files with a `.php` extension will be scanned.
```json
{
    "source-providers": [
        {
            "in": ". as current",
            "name": "/\\.php$/",
            "exclude": "vendor"
        }
    ],
    "plugins": [
    ],
    "analysers": [
    ],
    "services": [
    ]
}
```

**Comment by jrfnl** [comment]
The file is located in the root of the project and the project is scanned with `.` as the path. The php files in the project are in subdirectories.

**Comment by llaville** [comment]
While I analysed this issue, I found that the doc is incomplete. If you want to exclude some files, use "notName" , with same syntax (regexp) as with "name".

see https://github.com/llaville/php-reflect/blob/master/src/Bartlett/Reflect/Api/V3/Common.php#L162

**Comment by jrfnl** [comment]
@llaville Thanks for getting back to me. I'll give it a try. All the same, I don't "tell" the program to include `inc` files and explicitly tell it to only include `php` files, so, if I change it to `notName: "/\\.inc$/"`, it still doesn't explain why `inc` files were being included in the first place or what other file extensions will be magically included in the scan.

**Comment by llaville** [comment]
@jrfnl I will investigate deeper. But to resume php-compatinfo config system (use php-reflect base package) is a wrapper to symfony/finder component to file or exclude files.

I've tried to add common symfony features. Perharps I'm wrong: I'll check later today and give you a feedback.

**Comment by pattisahusiwa** [comment]
Please check this line of code: 
https://github.com/llaville/php-reflect/blob/master/src/Bartlett/Reflect/Api/V3/Common.php#L98

When executing `phpcompatinfo analyser:run` without any source, `phpcompatinfo` will complain about it. Therefore, I think `$provider` will always has a value. Hence, the source code inside 
```if (!isset($provider)) {``` will not be executed.

I have the same issue, `phpcompatinfo.json` is completely not respected. Commenting out the line and make sure we have `in` key in `source-providers` fix the issue.

**Comment by llaville** [comment]
Thanks to all, but I'll close this issue that won't be fixed, because I've let down JSON config file, in next version 5.4
I've already implemented the new feature (`--config` option) that use the `symfony/dependency-injection` component
