### ISSUE TITLE
Upgrade to Box3

### ISSUE THREAD

**Issue by theofidry** [llaville/php-compat-info#244]
Hi,

Just a word to say you could switch from Box2 to [Box3](https://github.com/humbug/box). I couldn't really find how the PHARs are being built or which version of PHPUnit is used so I did not provide a PR. However I'll be happy to help if you are willing to upgrade. You can see the list of new features on the readme as well as an upgrade guide

**Comment by llaville** [comment]
Hello Théo,

Life if very funny. Yesterday, I've talked about your project/fork from Original Box2 to a colleague on one of his project. And told him that it will be nice to adopt Box 3 :-)

I mark it on my TODO list. I'm currently working on php-compatinfo-db.
 
Laurent

**Comment by llaville** [comment]
Commit https://github.com/llaville/php-compat-info/commit/6faabf72313c962adb256c311d1e6bc086ba08de do the job
