### ISSUE TITLE
Cannot fully understand the Result

### ISSUE THREAD

**Issue by mayeenulislam** [llaville/php-compat-info#246]
I love the php-compat-info tool. Used it previously on my other plugins.

But recently after running the `phpcompatinfo analyser:run .` command in one of my WordPress plugin (containing third-party libraries), the result appeared is:

> Requires PHP 5.3.0 (min), PHP 4.4.9 (max), PHP 7.0.2 (all)

I actually can't understand the result.

- If the `v4.4.9` is the max then what are the `v5.3.0` and `v7.0.2`?
- What exactly is the **minimum PHP version requirement** of my code?

**Comment by llaville** [comment]
hello. is your code open sourced ? could i have access to analyse it ?

Normally min version should be lower than max. And full version count all code including conditional that may be optional.

**Comment by mayeenulislam** [comment]
## Screenshot
![odd-requirements](https://user-images.githubusercontent.com/4551598/52525006-771fc780-2ccd-11e9-95ae-5fd8ac42126e.png)

Actually, the code I tested with, is a premium version of my plugin, is not publicly available.

## New Observation
After your query, I got skeptic too. And retest differently in the same code.

Just cloned the git repo and tested there. It worked just fine, and displayed:
> Requires PHP 5.2.0 (min), PHP 7.0.2 (all)

![good-requirements](https://user-images.githubusercontent.com/4551598/52525041-f01f1f00-2ccd-11e9-9b42-e90bbf2d9813.png)

Same thing happened to my publicly available code too: [NanoSupport](https://github.com/nanodesigns/nanosupport).

## Anomaly
But the same issue present when I run the test in the development environment, where there are other files too. I can list the type of files that are different from the git repo:

- `.css` (minified files)
- `.js` (uglified files)
- `.sublime-project` (Sublime Text project setup file)
- `.sublime-workspace` (Sublime Text workspace cache file)
- `/node_modules` (Huge collection of node modules)

## Found the culprit
I tested in my new repo. You can test it in the public repo.

**Steps to Reproduce:**

1. Clone the public [Github repo](https://github.com/nanodesigns/nanosupport)
2. Run `phpcompatinfo analyser:run .` (it will produce a solid result)
3. Run the `npm install`
4. Run `phpcompatinfo analyser:run .` (it will produce the bad result)

**The culprit is the `node_modules`.**

![final-result](https://user-images.githubusercontent.com/4551598/52525211-6f155700-2cd0-11e9-9b37-83a0263d5ec2.png)

**Comment by llaville** [comment]
Good analysis report. Thanks!
So we can suspect that node_modules install other php scripts files.
To solve, use a json phpcompatinfo config file and exclude some directories from scan.
