### ISSUE TITLE
Allow bartlett/php-compatinfo-db 2 ?

### ISSUE THREAD

**Issue by remicollet** [llaville/php-compat-info#247]
What are the plan to allow new bartlett/php-compatinfo-db version 2 ?
(allowing ^1.25 || ^2.0 will be nice)

Mostly because 1.x doesn't receive any update, so we are sticked on an outdated version.

I understand that some major changes are planed (for 6.0), but nice to have a 5.x update including this.

**Comment by llaville** [comment]
Hello Remi,
I understand your point of view, and that the situation is a bit complicated. I've less free time, and i prefer to use it to new major versions. 
I've a full roadmap with Umlwriter 2.0 (PHP 7.1+) then Reflect 5.0 (PHP 7.1+) then CompatInfo 6.0 (PHP 7.1+ with CompatInfoDb 2.0 PHP 7.1+)

I'll backport CompatInfoDb 2.0 to 1.x in the next week.

**Comment by llaville** [comment]
PHP-CompatInfo 5.1 will not support PHP-CompatInfo-Db 2

I'll publish in next minutes, version 1.40 synchronised with content of  PHP-CompatInfo-Db 2.1

**Comment by llaville** [comment]
PHP-CompatInfo-Db 1.40.0 has just been released. 
Feel free to close this issue if all is ok for you !

**Comment by remicollet** [comment]
If php-compatinfo-db 1.x is maintained until Compatininfo v6, that's fine for me

**Comment by llaville** [comment]
This is what i've in mind, even if i have twice job to do
