### ISSUE TITLE
ReflectionType is not recognized

### ISSUE THREAD

**Issue by pattisahusiwa** [llaville/php-compat-info#250]
`ReflectionType` is introduced in PHP 7. However, CompatInfo shows that `ReflectionType` is a user defined class.

```
Classes Analysis

    Class                           Matches REF        EXT min/Max PHP min/Max PHP all 
  U ReflectionType                  1       user                   4.0.0  
```

Tested on Arch Linux.
```
PHP 7.3.6 (cli) (built: May 28 2019 16:47:07) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.6, Copyright (c) 1998-2018 Zend Technologies
    with Xdebug v2.7.2, Copyright (c) 2002-2019, by Derick Rethans
```

```
phpCompatInfo version 5.1-dev DB version 2.5.0 built Jun 15 2019 10:25:42 CEST
```

**Comment by llaville** [comment]
Thanks for reporting. I'll check this tomorrow.

**Comment by llaville** [comment]
I've added missing Reflection classes in compatinfo database

- ReflectionClassConstant   7.1.0 alpha1
- ReflectionNamedType       7.1.0 beta3
- ReflectionType            7.0.0 alpha1
- ReflectionGenerator       7.0.0 alpha1

In waiting next release 2.6.0 of CompatInfo Database, that will come shortly in end of month with PHP 7.3.7, you can in the meantime build your DB sqlite file.

Follow instructions:

- build DB with command `bin/compatinfo-db bartlett:db:init`
-  you can check that you have missing classes by running command `bin/compatinfo-db bart:db:show reflection --classes`
- copy `data/compatinfo.sqlite` file from your compatinfo-db project to compatinfo project

**Comment by pattisahusiwa** [comment]
Thank you. I'll waiting for the next release.

**Comment by llaville** [comment]
@pattisahusiwa FYI: CompatInfo DB 2.6.0 has just been released
