### ISSUE TITLE
missing phar releases after 5.0.12

### ISSUE THREAD

**Issue by DanielRuf** [llaville/php-compat-info#251]
It seems the new releases are missing.

**Comment by llaville** [comment]
Don't think so: did you tried to get it at http://bartlett.laurent-laville.org/get/phpcompatinfo-5.0.12.phar

**Comment by llaville** [comment]
And latest version is available at http://bartlett.laurent-laville.org/get/phpcompatinfo-5.1.0.phar

**Comment by llaville** [comment]
Just version 5.2.0 is missing

**Comment by DanielRuf** [comment]
> And latest version is available at http://bartlett.laurent-laville.org/get/phpcompatinfo-5.1.0.phar

Right but it seems it is not linked on the website or did I oversee it? "Download latest version" links to 5.0.12.

**Comment by llaville** [comment]
Right, site http://php5.laurent-laville.org/compatinfo/ was a bit outdated. Github project page https://github.com/llaville/php-compat-info is more up-to-date !

**Comment by LucasKovacs** [comment]
How can I get the phpcompatinfo-5.2.0.phar file?

**Comment by DanielRuf** [comment]
Good question =)

**Comment by LucasKovacs** [comment]
I saw that there's a 5.2.0 release here https://github.com/llaville/php-compat-info/releases, but I don't know how to build that, when I tried it seems that I'm missing many libraries. It's also the only library that detects PHP 7

**Comment by DanielRuf** [comment]
> Just version 5.2.0 is missing

https://github.com/llaville/php-compat-info/issues/251#issuecomment-521522951

**Comment by LucasKovacs** [comment]
@llaville can you share the 5.2.0 version? Or explain to us how we can build it from the releases page

**Comment by llaville** [comment]
I will explain how to do. And build a copy in few hours (tonight for me. French Hours)

**Comment by llaville** [comment]
To build PHAR distribution, you'll need to get a copy of this project https://github.com/humbug/box

`box.phar compile`  in the php-compat-info project directory will build phar version. 

Example:
```
    ____            
   / __ )____  _  __
  / __  / __ \| |/_/
 / /_/ / /_/ />  <  
/_____/\____/_/|_|  
                    

Box version 3.8.0@e7d8df3 2019-06-08 14:25:00 UTC

 // Loading the configuration file "/shared/backups/php/php-compat-info/box.json.dist".                                 

🔨  Building the PHAR "/shared/backups/php/php-compat-info/bin/phpcompatinfo.phar"

? Removing the existing PHAR "/shared/backups/php/php-compat-info/bin/phpcompatinfo.phar"
? No compactor to register
? Adding main file: /shared/backups/php/php-compat-info/bin/phpcompatinfo
? Adding requirements checker
? Adding binary files
    > No file found
? Auto-discover files? No
? Exclude dev files? No
? Adding files
    > 993 file(s)
? Using stub file: /shared/backups/php/php-compat-info/phar-stub.php
? Skipping dumping the Composer autoloader
? Removing the Composer dump artefacts
? Compressing with the algorithm "GZ"
    > Warning: the extension "zlib" will now be required to execute the PHAR
? Setting file permissions to 0755
* Done.

No recommendation found.
No warning found.

 // PHAR: 1019 files (1.45MB)                                                                                           
 // You can inspect the generated PHAR with the "info" command.                                                         

 // Memory usage: 21.35MB (peak: 22.32MB), time: <1sec                                                                  
```

PHP CompatInfo 5.2.1 will be release in next minutes now. Sorry documentations are a bit outdated !
I've no time to update-it

**Comment by llaville** [comment]
5.2.1 has just been released. And phar distribution was built and available to download via project home page
