### ISSUE TITLE
How to upgrade the DB?

### ISSUE THREAD

**Issue by LucasKovacs** [llaville/php-compat-info#252]
@llaville 

I've successfully installed the newer version of php-compat-info to 5.2.1 but it's still using the DB version 2.x-dev@effa54c.

`phpcompatinfo -V
phpCompatInfo version 5.2.1 DB version 2.x-dev@effa54c built Jun 26 2019 17:35:50 CEST`

How can I upgrade that DB to 2.6.0 referenced here https://github.com/llaville/php-compatinfo-db

I assume that it's the last thing that I am missing since it won't recognize beyond PHP 5.6

**Comment by llaville** [comment]
For standard distribution, you just have to update `bartlett/php-compatinfo-db` dependency.

``` composer update bartlett/php-compatinfo-db```
Example:
```bash
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Updating bartlett/php-compatinfo-db (2.4.0 => 2.6.0): Downloading (100%)         
Writing lock file
Generating optimized autoload files
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
```
And check it with command ```php bin/phpcompatinfo --version```
That give something like
```phpCompatInfo version 5.2.1 DB version 2.6.0 built Jul 25 2019 20:04:40 CEST```

If you want a PHAR distribution, you have to build with procedure explained in 
https://github.com/llaville/php-compat-info/issues/251#issuecomment-544645733 

Hope it will help!

**Comment by LucasKovacs** [comment]
@llaville thanks for your help. I've finally managed to build the .phar with the 2.6 db. Although I think I am missing something. The script still returns PHP 5.6 as the max version which is not possible since I'm using PHP 7.1 code.

`phpCompatInfo version 5.2.1 DB version 2.6.0 built Jul 25 2019 20:04:40 CEST`

> Requires PHP 5.6.0 (min), PHP 5.6.0 (all)

**Comment by llaville** [comment]
Version detection of your code is another subject. So i'll close this thread !
