### ISSUE TITLE
Version detection issue

### ISSUE THREAD

**Issue by LucasKovacs** [llaville/php-compat-info#253]
@llaville I'm running version 5.2.1 with 2.6.0 DB. The script still returns PHP 5.6 as the max version which is not possible since I'm using PHP 7.1 specific syntax.

`phpCompatInfo version 5.2.1 DB version 2.6.0 built Jul 25 2019 20:04:40 CEST`

> Requires PHP 5.6.0 (min), PHP 5.6.0 (all)

What Am I missing here?

**Comment by llaville** [comment]
Sorry, but without context (source code analysed) I cannot help you !
If source code is available, please provide a link. If not feel free to close this issue.

**Comment by LucasKovacs** [comment]
@llaville take any of these files as an example

https://github.com/XGProyect/XG-Proyect-v3.x.x/blob/310-phase-3/src/upload/application/controllers/game/preferences.php

https://github.com/XGProyect/XG-Proyect-v3.x.x/blob/310-phase-3/src/upload/application/core/enumerators/PreferencesEnumerator.php

**Comment by llaville** [comment]
@LucasKovacs  Yes you're right. PHP-CompatInfo 5.0.x does not support full PHP 7 detection.

Major release 6.0 is supposed to do it, but I need to rewrite it to simplify architecture.
But i need free times, and don't have it actually !

Probably in next months, but I cannot tell you a date

**Comment by LucasKovacs** [comment]
thanks @llaville will be waiting
