### ISSUE TITLE
PHP7 null coalesce operator not detected

### ISSUE THREAD

**Issue by lkrms** [llaville/php-compat-info#260]
Using code like:

```php
$something = $that['thing']??null;
```

Should return PHP 7.0 (min), but PHP 5.5.0 is returned on my system (I'm using PHP 7.4).

**Comment by llaville** [comment]
Fixed with new bugfix release 5.2.2
Thanks for reporting.

**Comment by lkrms** [comment]
Impressive turnaround. Thank you :)
