### ISSUE TITLE
Mass method signature mismatch

### ISSUE THREAD

**Issue by szepeviktor** [llaville/php-compat-info#286]
Please consider running `phpstan analyze src/ -l 2`

( fastest way to get there: `phive install phpstan` )

Many classes do not match `PhpParser\NodeVisitor`

**Comment by llaville** [comment]
It's a QA process that will be apply in v6.
I won't spend more time than necessary on v5.4 
Anyway thanks for your recommandation

**Comment by llaville** [comment]
Commits : 
- 1b41515ab0ae07ef1c0591f024349ea46c273f46 fixed phpstan analysis on level 0
- 464b0cf34c8504e66f5d5dd033ad2af770e481ac fixed phpstan analysis on level 1
- e6e87328110810f0eab68571d65f1338a2e414ff  fixed phpstan analysis on level 2
- dce604aa4bb9d6fe3eef124131236e33df4230f5 introduced phpstan config file

**Comment by szepeviktor** [comment]
https://twitter.com/szepeviktor/status/1359481979092230144 👁️‍🗨️

**Comment by llaville** [comment]
Feel free to close this issue, if it look good to you !

**Comment by szepeviktor** [comment]
Thank you for your work.
