### ISSUE TITLE
Method signature inheritance issue

### ISSUE THREAD

**Issue by szepeviktor** [llaville/php-compat-info#294]
`AbstractSniffAnalyser::beforeTraverse` has `{@inheritDoc}` and ❗ it works 😃 

`PhpParser\NodeVisitor::beforeTraverse` looks like 

https://github.com/nikic/PHP-Parser/blob/master/lib/PhpParser/NodeVisitor.php#L7-L18

so we should return `null|Node[]` and phpstan tells us exactly that.

```
  62     Method Bartlett\CompatInfo\Application\Analyser\AbstractSniffAnalyser::beforeTraverse() should return
         array<PhpParser\Node>|null but return statement is missing.
```

Adding a `return` statement will resolve this and all other problems of this kind.

**Comment by llaville** [comment]
Thanks for PR !

**Comment by llaville** [comment]
on my way to adds return null missing !

**Comment by szepeviktor** [comment]
# 🚂🚂🚂
