### ISSUE TITLE
bug 

### ISSUE THREAD

**Issue by Anandh21** [llaville/php-compat-info#299]
hi, 
I want  to analyse a laravel project.
but when i run php-compat i have this error 
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /vendor/nikic/php-parser/lib/PhpParser/Parser/Php7.php on line 2174

**Comment by llaville** [comment]
If you can't provide such information, I'll close this issue because without contextual data, I can't help you !
