### ISSUE TITLE
No way to filter source directory

### ISSUE THREAD

**Issue by sebastianmacarescu** [llaville/php-compat-info#305]
## Summary
I can't find any example on how to use the --config to filter out stuff from source directory.
I don't want to scan the vendor directory for example.
I see that was possible in <5.4 using the json config file but now that is removed.

**Comment by llaville** [comment]
if answer https://github.com/llaville/php-compat-info/discussions/304#discussioncomment-556911 does not match your need, please specify all informations as defined in template please

**Comment by llaville** [comment]
@sebastianmacarescu FYI feature is implemented and available on branch 5.5 (in waiting future release that should come in few days)

**Comment by llaville** [comment]
Feature is now also implemented on branch 6.0
