### ISSUE TITLE
Unable to run since version 5.5.0

### ISSUE THREAD

**Issue by yuri-ccp** [llaville/php-compat-info#307]
## OS
1. Host operating system and version: Centos 7/8
2. PHP version: 7.3.28
3. PHP CompatInfo version: 5.5.3

Since version 5.5.0 to 5.5.3 I can't run `phpcompatinfo analyser:run` anymore. When I try to run it's returns the message:
Please setup database first

Until version 5.4.4 I just need to install the phpcompatinfo using composer e begin to use it. But know it's requires to build it's database and some workaround to it find the vendor directory. But even after that it don't have the sqlite database anymore. I tried to manually build it with `vendor/bin/doctrine orm:schema-tool:create` and `compatinfo-db db:init` but I only receive  unable to open database file erros.

**Comment by llaville** [comment]
composer run post-install-cmd will rebuild your sqlite database.
If you want to use another database engine, please have a look on php-compatinfo-db project

**Comment by yuri-ccp** [comment]
It's works! Thank you!

Maybe is interesting to add this to README.md. Once that run `composer require bartlett/php-compatinfo` is not more enough to run/update de compatinfo installations.

**Comment by llaville** [comment]
README page was just updated !
